INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski de fond Goms', 'Oberwald', 'sport', '100 km de pistes de ski de fond dans la haute vallée du Rhône. Site nordique réputé.', 46.5314, 8.3614, 240, 3, ARRAY['Parking'], ARRAY['Hiver'], ARRAY['Famille','Solo','Couple'], false, true, 'https://www.obergoms.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[12,1,2,3]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski de fond Goms' AND location_name = 'Oberwald') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski de fond Goms' AND location_name = 'Oberwald');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Téléphérique Mittelallalin', 'Saas-Fee', 'sport', 'Plus haut métro souterrain du monde (3500m). Restaurant tournant, glacier 360°.', 46.1086, 7.9272, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Été','Hiver','Automne'], ARRAY['Couple','Amis','Famille'], true, true, 'https://www.saas-fee.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Téléphérique Mittelallalin' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Téléphérique Mittelallalin' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Pont suspendu Charles Kuonen', 'Randa', 'adventure', 'Plus long pont suspendu piéton du monde (494m, 85m de haut). Frissons garantis.', 46.0917, 7.7972, 240, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Amis'], false, true, 'https://www.randa.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Pont suspendu Charles Kuonen' AND location_name = 'Randa') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Pont suspendu Charles Kuonen' AND location_name = 'Randa');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Via ferrata Saillon', 'Saillon', 'adventure', 'Via ferrata facile à difficile dans une falaise. Vue plaine du Rhône.', 46.175, 7.1833, 180, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Solo','Amis'], false, true, 'https://www.saillon.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Via ferrata Saillon' AND location_name = 'Saillon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Via ferrata Saillon' AND location_name = 'Saillon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Via ferrata Loèche-les-Bains', 'Loèche-les-Bains', 'adventure', '3 itinéraires de via ferrata avec vue sur les Alpes valaisannes.', 46.385, 7.6311, 240, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Solo','Amis'], false, true, 'https://www.leukerbad.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Via ferrata Loèche-les-Bains' AND location_name = 'Loèche-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Via ferrata Loèche-les-Bains' AND location_name = 'Loèche-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Canyoning Saillon', 'Saillon', 'adventure', 'Canyoning dans les gorges de la Salentse. Cascades, sauts, toboggans.', 46.175, 7.1833, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Amis'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Canyoning Saillon' AND location_name = 'Saillon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Canyoning Saillon' AND location_name = 'Saillon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Canyoning Sierre', 'Sierre', 'adventure', 'Plusieurs niveaux de canyoning sur les rivières de la région.', 46.2925, 7.5356, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Amis'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Canyoning Sierre' AND location_name = 'Sierre') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Canyoning Sierre' AND location_name = 'Sierre');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Parapente Verbier', 'Verbier', 'adventure', 'Vol biplace au-dessus de la vallée. Plusieurs sites de décollage selon la météo.', 46.0961, 7.2286, 90, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Solo','Amis'], false, true, 'https://www.flyverbier.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Parapente Verbier' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Parapente Verbier' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Parapente Crans-Montana', 'Crans-Montana', 'adventure', 'Vol biplace face aux Alpes valaisannes. Décollage du Bella Lui (2543m).', 46.3117, 7.4853, 90, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Solo','Amis'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Parapente Crans-Montana' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Parapente Crans-Montana' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Tyrolienne Sky Glide Crans', 'Crans-Montana', 'adventure', 'Tyrolienne quadruple à Crans-Montana. Vitesse à 90 km/h sur 2 km.', 46.3117, 7.4853, 60, 4, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Amis','Famille'], false, true, 'https://www.crans-montana.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Tyrolienne Sky Glide Crans' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Tyrolienne Sky Glide Crans' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Saut élastique Verbier', 'Verbier', 'adventure', 'Saut depuis le téléphérique au-dessus du barrage de Mauvoisin (180m).', 46.0833, 7.4111, 60, 5, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Amis','Solo'], false, true, 'https://www.verbier.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Saut élastique Verbier' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Saut élastique Verbier' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Glacier hike Aletsch', 'Bettmeralp', 'adventure', 'Randonnée encadrée sur le glacier d''Aletsch. Crampons fournis, accompagnement guide.', 46.4361, 8.0386, 360, 5, ARRAY['Reservation necessaire','Minimum de participants'], ARRAY['Été','Automne'], ARRAY['Solo','Amis','Couple'], false, true, 'https://www.aletscharena.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Glacier hike Aletsch' AND location_name = 'Bettmeralp') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Glacier hike Aletsch' AND location_name = 'Bettmeralp');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Loèche-les-Bains thermes', 'Loèche-les-Bains', 'relax', 'Plus grand centre thermal des Alpes. 3.9 millions L/jour à 51°C. 30 bassins.', 46.385, 7.6311, 240, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille','Solo'], true, true, 'https://www.leukerbad.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Loèche-les-Bains thermes' AND location_name = 'Loèche-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Loèche-les-Bains thermes' AND location_name = 'Loèche-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bains de Brigerbad', 'Brig-Glis', 'relax', 'Plus ancien centre thermal du Valais. Toboggan thermal (eau chaude !), grottes, jacuzzi.', 46.3056, 7.9694, 180, 4, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, true, 'https://www.thermalbad-brigerbad.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bains de Brigerbad' AND location_name = 'Brig-Glis') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bains de Brigerbad' AND location_name = 'Brig-Glis');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bains thermaux d''Ovronnaz', 'Ovronnaz', 'relax', 'Centre thermal en montagne (1400m). Bassins panoramiques face aux Alpes.', 46.1922, 7.1644, 180, 4, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, true, 'https://www.thermalp.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bains thermaux d''Ovronnaz' AND location_name = 'Ovronnaz') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bains thermaux d''Ovronnaz' AND location_name = 'Ovronnaz');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Mont-Cervin', 'Zermatt', 'relax', 'Spa cinq étoiles avec piscine intérieure, hammam. Vue Cervin depuis le bassin.', 46.0207, 7.7491, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.montcervinpalace.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Mont-Cervin' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Mont-Cervin' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Crans Ambassador', 'Crans-Montana', 'relax', 'Spa de luxe avec piscine, sauna, hammam, soins. Vue Alpes valaisannes.', 46.3117, 7.4853, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.cransambassador.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Crans Ambassador' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Crans Ambassador' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Aqua-Spa Loèche-les-Bains', 'Loèche-les-Bains', 'relax', 'Centre wellness moderne avec piscines à différentes températures, sauna, hammam.', 46.3833, 7.63, 240, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Solo'], true, true, 'https://www.leukerbad.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Aqua-Spa Loèche-les-Bains' AND location_name = 'Loèche-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Aqua-Spa Loèche-les-Bains' AND location_name = 'Loèche-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Lindner Zermatt', 'Zermatt', 'relax', 'Spa de l''hôtel Lindner avec vue Cervin. Piscine extérieure chauffée même en hiver.', 46.0207, 7.7491, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.lindnerhotels.com', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Lindner Zermatt' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Lindner Zermatt' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Anzère Spa & Wellness', 'Anzère', 'relax', 'Centre wellness avec piscine, sauna, hammam. Vue plongeante sur la vallée.', 46.2842, 7.4108, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.anzere.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Anzère Spa & Wellness' AND location_name = 'Anzère') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Anzère Spa & Wellness' AND location_name = 'Anzère');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Labyrinthe Aventure', 'Évionnaz', 'fun', 'Plus grand labyrinthe végétal de Suisse. Énigmes pour tous âges, parc pour enfants.', 46.1839, 7.0314, 180, 3, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Amis'], false, true, 'https://www.labyrinthe.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[4,5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Labyrinthe Aventure' AND location_name = 'Évionnaz') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Labyrinthe Aventure' AND location_name = 'Évionnaz');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Adventure Park Hannig', 'Saas-Fee', 'fun', 'Parc d''aventure : tyrolienne géante, trottinettes, sentiers thématiques pour familles.', 46.1086, 7.9272, 240, 4, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille','Amis'], false, true, 'https://www.saas-fee.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Adventure Park Hannig' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Adventure Park Hannig' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Zoo Alpin des Marécottes', 'Salvan', 'fun', 'Petit zoo alpin avec lynx, loups, ours bruns. Cadre de montagne authentique.', 46.11, 7.0164, 180, 3, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille'], false, true, 'https://www.zoo-alpin.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Zoo Alpin des Marécottes' AND location_name = 'Salvan') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Zoo Alpin des Marécottes' AND location_name = 'Salvan');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Foire du Valais', 'Martigny', 'event', 'Plus grande foire de Suisse romande, en octobre. Combats de reines, gastronomie locale.', 46.1011, 7.075, 240, 2, ARRAY['Parking'], ARRAY['Automne'], ARRAY['Famille','Amis'], false, true, 'https://www.foireduvalais.ch', NULL, 'loc_lower', 'Début octobre 2026', 'Early October 2026', '2026-10-02'::date, '2026-10-11'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Foire du Valais' AND location_name = 'Martigny') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Foire du Valais' AND location_name = 'Martigny');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Festival International de Cor des Alpes', 'Nendaz', 'event', 'Plus grand rassemblement mondial de cors des Alpes en juillet. Concerts gratuits.', 46.1839, 7.3092, 240, 1, ARRAY[]::text[], ARRAY['Été'], ARRAY['Famille','Couple','Solo','Amis'], false, true, 'https://www.cor-des-alpes.ch', NULL, 'loc_central', 'Mi-juillet 2026', 'Mid-July 2026', '2026-07-17'::date, '2026-07-19'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Festival International de Cor des Alpes' AND location_name = 'Nendaz') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Festival International de Cor des Alpes' AND location_name = 'Nendaz');
