INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Aquatis Aquarium-Vivarium', 'Lausanne', 'fun', 'Plus grand aquarium-vivarium d''eau douce d''Europe. 10 000 animaux, 20 ecosystemes recreces. Note Google 4.3.', 46.5417, 6.6486, 180, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.aquatis.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Aquatis Aquarium-Vivarium' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Aquatis Aquarium-Vivarium' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Train Belle Époque GoldenPass', 'Montreux', 'fun', 'Train panoramique vintage Montreux-Zweisimmen, voitures restaurees Belle Epoque. Vue Alpes, Pre-Alpes, Lavaux.', 46.4339, 6.9119, 240, 4, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.goldenpass.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Train Belle Époque GoldenPass' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Train Belle Époque GoldenPass' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Train du Chocolat', 'Montreux', 'fun', 'Train touristique GoldenPass de Montreux a la chocolaterie Cailler de Broc. Inclus visite et degustation.', 46.4339, 6.9119, 480, 5, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.goldenpass.ch', NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Train du Chocolat' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Train du Chocolat' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bateau Belle Époque CGN', 'Lausanne-Ouchy', 'fun', 'Croisiere a bord d''un bateau a vapeur classe (Simplon, Italie, Savoie...). Ambiance Belle Epoque, traversee Leman.', 46.5083, 6.6261, 180, 3, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Amis'], true, true, 'https://www.cgn.ch', NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[4,5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bateau Belle Époque CGN' AND location_name = 'Lausanne-Ouchy') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bateau Belle Époque CGN' AND location_name = 'Lausanne-Ouchy');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Karting Lausanne', 'Crissier', 'fun', 'Piste de karting indoor de Crissier, 600m. Karts puissants, courses chronometrees, sessions arcade pour enfants.', 46.5497, 6.5775, 90, 4, ARRAY['Parking','Reservation necessaire','Minimum de participants'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis','Famille'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Karting Lausanne' AND location_name = 'Crissier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Karting Lausanne' AND location_name = 'Crissier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Laser Game Lausanne', 'Lausanne', 'fun', 'Centre de laser game multi-niveaux a Lausanne. Decors thematiques, parties d''equipes, ideal anniversaires.', 46.5202, 6.6306, 60, 3, ARRAY['Reservation necessaire','Minimum de participants'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Laser Game Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Laser Game Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Jumpville Lausanne', 'Lausanne', 'fun', 'Trampoline park indoor a Lausanne : 2''500 m² de trampolines, free jump, dodgeball, slamball pour tous ages.', 46.54, 6.62, 90, 3, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis'], true, false, 'https://www.jumpville.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Jumpville Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Jumpville Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bowling Lausanne Centre', 'Lausanne', 'fun', 'Centre de bowling a Lausanne. 14 pistes, billard, restaurant, animations weekend.', 46.524, 6.632, 90, 3, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis','Couple'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bowling Lausanne Centre' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bowling Lausanne Centre' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cinéma Pathé Flon', 'Lausanne', 'fun', 'Multiplexe Pathé du Flon (12 salles, IMAX, 4DX). L''un des plus gros cinemas de Suisse romande.', 46.5202, 6.6306, 120, 3, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis','Solo'], true, false, 'https://www.pathe.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cinéma Pathé Flon' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cinéma Pathé Flon' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cinéma Capitole', 'Lausanne', 'fun', 'Plus grand cinéma à salle unique de Suisse, monument historique. Programmation art-et-essai et grand public.', 46.5197, 6.6306, 120, 3, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis','Solo'], true, false, 'https://www.capitolelausanne.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cinéma Capitole' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cinéma Capitole' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Casino Barrière Montreux', 'Montreux', 'fun', 'Casino emblematique de Montreux. Machines a sous, jeux de table, bar, restaurant, programmation evenementielle.', 46.4316, 6.9124, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.casinosbarriere.com/fr/montreux.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Casino Barrière Montreux' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Casino Barrière Montreux' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Train à vapeur Blonay-Chamby', 'Blonay', 'fun', 'Train a vapeur historique entre Blonay et Chamby (mai-octobre). Locomotives centenaires, musee ferroviaire en gare.', 46.4628, 6.9103, 180, 3, ARRAY['Parking','Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple'], true, true, 'https://www.blonay-chamby.ch', NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Train à vapeur Blonay-Chamby' AND location_name = 'Blonay') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Train à vapeur Blonay-Chamby' AND location_name = 'Blonay');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Funiculaire Vevey-Mont Pèlerin', 'Vevey', 'fun', 'Funiculaire historique reliant Vevey au Mont Pèlerin. 10 minutes de monte, vue lac et Alpes au sommet.', 46.4633, 6.8492, 60, 2, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple'], true, false, 'https://www.mob.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Funiculaire Vevey-Mont Pèlerin' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Funiculaire Vevey-Mont Pèlerin' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Téléphérique Les Avants-Sonloup', 'Les Avants', 'fun', 'Petit telecabine touristique entre Les Avants et Sonloup, dans les hauts de Montreux. Vue Riviera et Dents-du-Midi.', 46.45, 6.97, 60, 2, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Téléphérique Les Avants-Sonloup' AND location_name = 'Les Avants') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Téléphérique Les Avants-Sonloup' AND location_name = 'Les Avants');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Karting Payerne', 'Payerne', 'fun', 'Piste outdoor de karting a Payerne, 1km. Karts adultes et enfants, courses endurance, ideal enterrement de vie.', 46.8228, 6.9433, 90, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Amis','Famille'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[4,5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Karting Payerne' AND location_name = 'Payerne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Karting Payerne' AND location_name = 'Payerne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Marché folklorique de Vevey', 'Vevey', 'fun', 'Marche d''ete sur la Grand-Place : produits du terroir, artisanat, animations folkloriques (samedis juillet-aout).', 46.4625, 6.8458, 120, 1, ARRAY['Horaires restreints'], ARRAY['Été'], ARRAY['Famille','Couple','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[7,8]::int[], ARRAY[6]::int[], 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Marché folklorique de Vevey' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Marché folklorique de Vevey' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Métro M2 Lausanne (touristique)', 'Lausanne', 'fun', 'Le M2, metro le plus pentu d''Europe (12% pente). Trajet panoramique Ouchy-Croisettes, attraction insolite.', 46.5083, 6.6261, 30, 1, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], true, false, 'https://www.t-l.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Métro M2 Lausanne (touristique)' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Métro M2 Lausanne (touristique)' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Smashland Lausanne', 'Lausanne', 'fun', 'Smash room a Lausanne. Casser des objets pour relacher le stress, equipement et combinaison fournis.', 46.54, 6.62, 60, 4, ARRAY['Reservation necessaire','Minimum de participants'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis','Couple'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Smashland Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Smashland Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Foire Habitat & Jardin Beaulieu', 'Lausanne', 'fun', 'Plus grand salon habitat de Suisse romande, mars chaque annee. 350 exposants, conferences, espaces decoration.', 46.53, 6.628, 240, 2, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.habitat-jardin.ch', NULL, NULL, 'Mars 2026', 'March 2026', '2026-03-07'::date, '2026-03-15'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Foire Habitat & Jardin Beaulieu' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Foire Habitat & Jardin Beaulieu' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Comptoir Suisse Beaulieu', 'Lausanne', 'fun', 'Foire commerciale de reference de Suisse romande. Salons themes (auto, loisirs, gastronomie), animations.', 46.53, 6.628, 240, 2, ARRAY['Parking','Horaires restreints'], ARRAY['Automne'], ARRAY['Famille','Couple','Amis'], true, false, NULL, NULL, NULL, 'Septembre 2026', 'September 2026', '2026-09-11'::date, '2026-09-20'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Comptoir Suisse Beaulieu' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Comptoir Suisse Beaulieu' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cinéma Bellevaux', 'Lausanne', 'fun', 'Cine-club historique de Lausanne. Programmation pointue, films d''auteur, debats post-projection. Atmosphere conviviale.', 46.5333, 6.6361, 120, 2, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Couple','Amis'], true, false, 'https://www.cinema-bellevaux.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cinéma Bellevaux' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cinéma Bellevaux' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Mini-golf Préverenges', 'Préverenges', 'fun', 'Parcours mini-golf 18 trous au bord du Leman. Ambiance familiale, restaurant terrasse, vue Mont-Blanc.', 46.5092, 6.5269, 90, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[4,5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Mini-golf Préverenges' AND location_name = 'Préverenges') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Mini-golf Préverenges' AND location_name = 'Préverenges');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Plage de Préverenges (été)', 'Préverenges', 'fun', 'Plage de sable, baignade Léman, beach-volley, locations paddle, snack. Spot estival familial très apprécié.', 46.5092, 6.5269, 240, 1, ARRAY['Parking'], ARRAY['Printemps','Été'], ARRAY['Famille','Couple','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Plage de Préverenges (été)' AND location_name = 'Préverenges') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Plage de Préverenges (été)' AND location_name = 'Préverenges');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Téléphérique Caux-Glion', 'Glion', 'fun', 'Funiculaire historique entre Glion et Caux. Vue panoramique sur Riviera, prolongement vers Rochers-de-Naye.', 46.4333, 6.9417, 60, 2, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple'], true, false, 'https://www.mob.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Téléphérique Caux-Glion' AND location_name = 'Glion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Téléphérique Caux-Glion' AND location_name = 'Glion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Marché de Lausanne (Riponne)', 'Lausanne', 'fun', 'Marche bi-hebdomadaire (mercredi et samedi) sur la Place de la Riponne. Produits du terroir, artisanat, ambiance.', 46.5236, 6.6336, 90, 1, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'weekly', NULL, ARRAY[3,6]::int[], 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Marché de Lausanne (Riponne)' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Marché de Lausanne (Riponne)' AND location_name = 'Lausanne');
