INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Collection de l''Art Brut', 'Lausanne', 'culture', 'Musée unique au monde dédié à l''art brut, créé par Jean Dubuffet en 1976. 70 000 oeuvres d''auteurs en marge.', 46.5278, 6.6217, 120, 2, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Couple'], true, false, 'https://www.artbrut.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Collection de l''Art Brut' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Collection de l''Art Brut' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée romain de Lausanne-Vidy', 'Lausanne', 'culture', 'Musée sur l''ancienne ville romaine de Lousonna. Mosaïques, statues, vie quotidienne dans l''antiquité.', 46.5181, 6.5928, 90, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo'], true, false, 'https://www.lausanne.ch/mrv', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée romain de Lausanne-Vidy' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée romain de Lausanne-Vidy' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée Jenisch', 'Vevey', 'culture', 'Musée d''art consacré aux estampes et au dessin, plus ancien musée des beaux-arts du canton (1897).', 46.4647, 6.85, 90, 2, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Couple'], true, false, 'https://www.museejenisch.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée Jenisch' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée Jenisch' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée historique de Vevey', 'Vevey', 'culture', 'Au château de l''Aile : histoire de la région, salle Brel, brasserie d''antan reconstituée.', 46.4625, 6.8458, 90, 2, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Famille'], true, false, 'https://www.museehistoriquevevey.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée historique de Vevey' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée historique de Vevey' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Maison d''Ailleurs', 'Yverdon-les-Bains', 'culture', 'Musée de la science-fiction, de l''utopie et des voyages extraordinaires. Unique en Europe, 4.4/5.', 46.7783, 6.6406, 120, 2, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Solo','Amis'], true, false, 'https://www.ailleurs.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Maison d''Ailleurs' AND location_name = 'Yverdon-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Maison d''Ailleurs' AND location_name = 'Yverdon-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Restaurant Anne-Sophie Pic au Beau-Rivage', 'Lausanne', 'gastronomy', 'Restaurant 3 étoiles Michelin de la chef la plus étoilée au monde. Expérience d''exception.', 46.5097, 6.6361, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.brp.ch/fr/restaurants-bars/anne-sophie-pic', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Restaurant Anne-Sophie Pic au Beau-Rivage' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Restaurant Anne-Sophie Pic au Beau-Rivage' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Caveau de Lavaux', 'Cully', 'gastronomy', 'Bar à vins coopératif gérant la cave communale. Plus de 50 vins de Lavaux à déguster.', 46.49, 6.7333, 120, 3, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.caveau-cully.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Caveau de Lavaux' AND location_name = 'Cully') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Caveau de Lavaux' AND location_name = 'Cully');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Brasserie La Bavaria', 'Lausanne', 'gastronomy', 'Institution lausannoise depuis 1908. Cuisine bistro suisse-bavaroise dans un décor Belle Époque.', 46.5217, 6.6328, 120, 3, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.bavaria-lausanne.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Brasserie La Bavaria' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Brasserie La Bavaria' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Le Pavé', 'Lausanne', 'gastronomy', 'Restaurant néo-bistro plébiscité, cuisine du marché. Service convivial dans un cadre intime.', 46.5217, 6.63, 120, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Le Pavé' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Le Pavé' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Café Romand', 'Lausanne', 'gastronomy', 'Brasserie historique depuis 1951. Spécialités vaudoises : papet, fondue, malakoff. Atmosphère traditionnelle.', 46.5197, 6.6328, 120, 2, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis','Couple'], true, false, 'https://www.caferomand.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Café Romand' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Café Romand' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'La Croix d''Or', 'Lutry', 'gastronomy', 'Restaurant gastronomique en bord de Léman. Carte de saison, terrasse spectaculaire en été.', 46.5028, 6.6856, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'La Croix d''Or' AND location_name = 'Lutry') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'La Croix d''Or' AND location_name = 'Lutry');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Auberge de l''Onde', 'Saint-Saphorin', 'gastronomy', 'Auberge centenaire dans les vignobles de Lavaux. Cuisine raffinée, vins de la propriété.', 46.4717, 6.7964, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.aubergedelonde.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Auberge de l''Onde' AND location_name = 'Saint-Saphorin') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Auberge de l''Onde' AND location_name = 'Saint-Saphorin');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Maison Cailler', 'Broc', 'gastronomy', 'Visite immersive de la chocolaterie centenaire. Histoire, dégustation à volonté en fin de parcours.', 46.6075, 7.0917, 90, 2, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.cailler.ch/fr/maison-cailler', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Maison Cailler' AND location_name = 'Broc') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Maison Cailler' AND location_name = 'Broc');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Domaine Henri Cruchon', 'Échichens', 'gastronomy', 'Domaine viticole familial, vins biodynamiques. Caveau de dégustation, visites guidées.', 46.5119, 6.4906, 90, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Amis'], true, false, 'https://www.henricruchon.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Domaine Henri Cruchon' AND location_name = 'Échichens') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Domaine Henri Cruchon' AND location_name = 'Échichens');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Brasserie de Montbenon', 'Lausanne', 'gastronomy', 'Brasserie réputée près du Casino de Montbenon. Ambiance vintage, terrasse avec vue sur le Léman.', 46.5189, 6.6286, 120, 3, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis','Famille'], true, true, 'https://www.brasseriedemontbenon.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Brasserie de Montbenon' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Brasserie de Montbenon' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Villars-Gryon', 'Villars-sur-Ollon', 'sport', '100 km de pistes accessibles à tous niveaux, vue sur le Mont-Blanc et les Dents du Midi.', 46.2972, 7.0481, 480, 5, ARRAY['Parking','Reservation necessaire'], ARRAY['Hiver'], ARRAY['Famille','Amis','Couple'], false, true, 'https://www.villars.ch', NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[12,1,2,3,4]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Villars-Gryon' AND location_name = 'Villars-sur-Ollon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Villars-Gryon' AND location_name = 'Villars-sur-Ollon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Leysin', 'Leysin', 'sport', '60 km de pistes, station ensoleillée face aux Dents du Midi. Snow park réputé.', 46.3478, 7.0089, 480, 5, ARRAY['Parking'], ARRAY['Hiver'], ARRAY['Famille','Amis'], false, true, 'https://www.leysin.ch', NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[12,1,2,3,4]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Leysin' AND location_name = 'Leysin') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Leysin' AND location_name = 'Leysin');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Les Diablerets', 'Les Diablerets', 'sport', 'Domaine relié à Glacier 3000. Ski toute l''année sur le glacier, panoramas exceptionnels.', 46.3553, 7.1572, 480, 5, ARRAY['Parking'], ARRAY['Été','Automne','Hiver'], ARRAY['Famille','Amis','Couple'], false, true, 'https://www.diablerets.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Les Diablerets' AND location_name = 'Les Diablerets') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Les Diablerets' AND location_name = 'Les Diablerets');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Aquaparc Le Bouveret', 'Le Bouveret', 'sport', 'Parc aquatique avec 12 toboggans, piscine à vagues. Le plus grand parc aquatique de Suisse romande.', 46.3839, 6.8472, 240, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été'], ARRAY['Famille','Amis'], false, true, 'https://www.aquaparc.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Aquaparc Le Bouveret' AND location_name = 'Le Bouveret') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Aquaparc Le Bouveret' AND location_name = 'Le Bouveret');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Patinoire de Malley', 'Lausanne', 'sport', 'Patinage public dans une grande patinoire moderne. Cours et sessions disco le weekend.', 46.5258, 6.5947, 120, 2, ARRAY['Parking','Horaires restreints'], ARRAY['Automne','Hiver','Printemps'], ARRAY['Famille','Amis'], true, false, 'https://www.vaudoisearena.ch', NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[10,11,12,1,2,3]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Patinoire de Malley' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Patinoire de Malley' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Voile et SUP Rolle', 'Rolle', 'sport', 'Centre nautique sur le Léman. Cours de voile, paddle, kitesurf. Locations à l''heure.', 46.4583, 6.3389, 180, 3, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Solo','Couple','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Voile et SUP Rolle' AND location_name = 'Rolle') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Voile et SUP Rolle' AND location_name = 'Rolle');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bike Park Villars', 'Villars-sur-Ollon', 'sport', 'Pistes VTT descentes, jumps et single tracks. Remontées mécaniques pour cyclistes.', 46.3, 7.05, 240, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Solo','Amis'], false, true, 'https://www.villars.ch/fr/ete/bike-park', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bike Park Villars' AND location_name = 'Villars-sur-Ollon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bike Park Villars' AND location_name = 'Villars-sur-Ollon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Centre Mountain Bike Lavaux', 'Chexbres', 'sport', 'Réseau de sentiers VTT à travers les vignes UNESCO. Locations possibles.', 46.4842, 6.7917, 240, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Solo','Amis','Couple'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Centre Mountain Bike Lavaux' AND location_name = 'Chexbres') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Centre Mountain Bike Lavaux' AND location_name = 'Chexbres');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Plage piscine de Morges', 'Morges', 'sport', 'Piscine olympique au bord du Léman. Bassins, plongeoirs, plage de gazon.', 46.5081, 6.5022, 180, 2, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été'], ARRAY['Famille','Amis','Couple'], false, true, 'https://www.morges.ch/fr/piscine', NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Plage piscine de Morges' AND location_name = 'Morges') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Plage piscine de Morges' AND location_name = 'Morges');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Centre sportif de Vidy', 'Lausanne', 'sport', 'Complexe sportif au bord du Léman. Tennis, mini-golf, escalade, plage. Idéal pour la journée.', 46.5172, 6.5917, 240, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Amis','Couple'], false, true, 'https://www.lausanne.ch/officiel/administration/sports-et-cohesion-sociale/centre-sportif-de-vidy.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Centre sportif de Vidy' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Centre sportif de Vidy' AND location_name = 'Lausanne');
