INSERT INTO public.activity_submissions (
  title, location_name, latitude, longitude, category, description,
  duration_minutes, price_level, is_indoor, is_outdoor,
  features, seasons, social_tags, location_zone, status, archived
) VALUES
-- ───── FRIBOURG VILLE & ENVIRONS ─────
('Vieille Ville de Fribourg', 'Fribourg (FR)', 46.8060, 7.1620, 'culture', 'Promenade dans la cité médiévale unique en Europe avec ses 200 façades gothiques, ses ruelles pavées et son funiculaire à eaux usées historique.', 120, 1, false, true, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Cathédrale Saint-Nicolas Fribourg', 'Fribourg (FR)', 46.8067, 7.1620, 'culture', 'Joyau gothique du XIIIe siècle avec ses vitraux remarquables, sa tour de 74m offrant une vue panoramique sur la ville et ses orgues réputées.', 90, 2, true, false, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Musée d''Art et d''Histoire de Fribourg', 'Fribourg (FR)', 46.8056, 7.1644, 'culture', 'Collections d''art religieux, peintures et sculptures retraçant l''histoire culturelle fribourgeoise du Moyen Âge à nos jours.', 120, 2, true, false, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Solo','Couple'], 'fribourg', 'pending', false),
('Espace Jean Tinguely - Niki de Saint Phalle', 'Fribourg (FR)', 46.8050, 7.1630, 'culture', 'Sculptures cinétiques de Tinguely et œuvres colorées de Niki de Saint Phalle dans un ancien dépôt de tram réaménagé.', 90, 2, true, false, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Musée Suisse de la Marionnette', 'Fribourg (FR)', 46.8085, 7.1610, 'culture,fun', 'Plus de 1000 marionnettes du monde entier exposées dans la maison de Tavel, avec spectacles réguliers et ateliers pour enfants.', 75, 2, true, false, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille'], 'fribourg', 'pending', false),
('Musée d''Histoire Naturelle Fribourg', 'Fribourg (FR)', 46.8004, 7.1605, 'culture,nature', 'Faune, flore et géologie de Suisse à travers de magnifiques dioramas, plus des fossiles et météorites exceptionnelles. Entrée libre.', 90, 1, true, false, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Solo'], 'fribourg', 'pending', false),
('Funiculaire Neuveville-Saint-Pierre', 'Fribourg (FR)', 46.8076, 7.1599, 'culture,fun', 'Funiculaire unique au monde fonctionnant aux eaux usées depuis 1899, classé monument historique. Trajet court mais original.', 30, 1, false, true, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple'], 'fribourg', 'pending', false),
('Pont de Berne', 'Fribourg (FR)', 46.8089, 7.1644, 'culture,nature', 'Pont couvert en bois du XVe siècle traversant la Sarine, un des plus anciens d''Europe encore en service. Vue magnifique sur la basse-ville.', 30, 1, false, true, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Bain de la Motta', 'Fribourg (FR)', 46.8025, 7.1583, 'sport,fun', 'Piscine en plein air historique avec bassins olympiques et plongeoirs, sur les rives de la Sarine. Ambiance estivale fribourgeoise.', 180, 2, false, true, ARRAY['Parking','Horaires restreints'], ARRAY['Été'], ARRAY['Famille','Amis'], 'fribourg', 'pending', false),
('Brasserie du Cardinal - Visite', 'Fribourg (FR)', 46.8023, 7.1490, 'culture,gastronomy', 'Découverte de l''histoire brassicole fribourgeoise dans l''ancien site Cardinal, avec dégustation incluse.', 90, 2, true, false, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis','Couple'], 'fribourg', 'pending', false),

-- ───── GRUYÈRES & PAYS-D'ENHAUT ─────
('Château de Gruyères', 'Gruyères (FR)', 46.5848, 7.0820, 'culture', 'Imposant château médiéval surplombant le village, avec ses jardins, ses fresques et l''exposition permanente sur l''histoire du comté de Gruyère.', 120, 2, true, true, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Musée HR Giger', 'Gruyères (FR)', 46.5850, 7.0810, 'culture', 'Musée dédié à l''artiste suisse H.R. Giger (Alien) avec ses œuvres biomécaniques exposées dans un bâtiment unique aux décors dystopiques.', 75, 2, true, false, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis','Couple','Solo'], 'fribourg', 'pending', false),
('Maison du Gruyère', 'Pringy-Gruyères (FR)', 46.5830, 7.0700, 'culture,gastronomy', 'Démonstration de fabrication du Gruyère AOP avec dégustation, ferme-école et restaurant traditionnel suisse.', 90, 2, true, false, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Maison Cailler', 'Broc (FR)', 46.6071, 7.1027, 'gastronomy,fun', 'Plus ancienne fabrique de chocolat de Suisse, visite immersive de A à Z avec dégustation illimitée à la fin. Coup de cœur familial.', 90, 2, true, false, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Village de Gruyères', 'Gruyères (FR)', 46.5847, 7.0823, 'culture,nature', 'Village médiéval piétonnier classé monument national, restaurants traditionnels et boutiques d''artisanat. Vue imprenable.', 180, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Moléson-sur-Gruyères', 'Moléson-sur-Gruyères (FR)', 46.5552, 7.0193, 'nature,adventure', 'Sommet emblématique avec funiculaire puis téléphérique, vue à 360° sur les Alpes et le Lavaux. Sentier botanique au sommet.', 240, 3, false, true, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Amis','Couple'], 'fribourg', 'pending', false),
('Devin la Fée Verte - Charmey', 'Charmey (FR)', 46.6190, 7.1665, 'nature', 'Cascade féerique au cœur de la vallée de Charmey, accès facile depuis le centre. Idéal pour une balade familiale.', 90, 1, false, true, ARRAY[]::text[], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple'], 'fribourg', 'pending', false),
('Bains de la Gruyère', 'Charmey (FR)', 46.6181, 7.1671, 'sport', 'Centre thermal moderne avec piscines intérieures et extérieures chauffées, hammam et saunas, vue sur les montagnes.', 180, 4, true, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille','Amis'], 'fribourg', 'pending', false),
('Vanil Noir', 'Charmey (FR)', 46.5654, 7.1383, 'nature,adventure', 'Plus haut sommet des Préalpes fribourgeoises (2389m), randonnée alpine exigeante avec faune locale (bouquetins, marmottes).', 480, 1, false, true, ARRAY[]::text[], ARRAY['Été','Automne'], ARRAY['Amis','Solo','Couple'], 'fribourg', 'pending', false),
('Lac de Montsalvens', 'Crésuz (FR)', 46.6262, 7.1521, 'nature', 'Lac d''émeraude entouré de falaises, sentier panoramique et pont suspendu (Berra). Promenade familiale d''environ 2h.', 150, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Sentier des Sculptures Charmey', 'Charmey (FR)', 46.6210, 7.1620, 'nature,culture', 'Parcours art en plein air avec œuvres monumentales en bois disséminées dans la forêt. Adapté familles.', 120, 1, false, true, ARRAY[]::text[], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Tyrolienne Moléson', 'Moléson-sur-Gruyères (FR)', 46.5552, 7.0193, 'adventure,fun', 'Tyrolienne géante de 1200m descendant le Moléson, sensations garanties avec vue panoramique sur la Gruyère.', 60, 4, false, true, ARRAY['Parking','Reservation necessaire','Minimum de participants','Horaires restreints'], ARRAY['Été','Automne'], ARRAY['Amis','Famille'], 'fribourg', 'pending', false),
('Parcours du fromage Pringy-Moléson', 'Pringy-Gruyères (FR)', 46.5700, 7.0500, 'nature,gastronomy', 'Sentier didactique de 6km traversant alpages et fermes laitières, avec panneaux explicatifs sur la fabrication du Gruyère.', 240, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Cailler Chocolaterie - Boutique d''usine', 'Broc (FR)', 46.6080, 7.1030, 'gastronomy', 'Boutique d''usine Cailler avec offres exclusives, dégustations et chocolats à prix promotionnels.', 60, 3, true, false, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis','Couple'], 'fribourg', 'pending', false),

-- ───── BULLE & SARINE ─────
('Musée Gruérien Bulle', 'Bulle (FR)', 46.6199, 7.0558, 'culture', 'Présentation de l''histoire et de la culture de la Gruyère, des arts populaires aux traditions montagnardes.', 90, 2, true, false, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Solo','Couple'], 'fribourg', 'pending', false),
('Vieille Ville Bulle', 'Bulle (FR)', 46.6193, 7.0565, 'culture', 'Cœur historique avec son château médiéval, ses ruelles pittoresques et ses cafés traditionnels.', 90, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Aérodrome d''Epagny', 'Epagny (FR)', 46.5963, 7.0961, 'adventure,sport', 'Vols découvertes en avion ou hélicoptère au-dessus des préalpes fribourgeoises, sensations garanties.', 60, 5, false, true, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Amis'], 'fribourg', 'pending', false),
('Téléphérique du Vounetz', 'Charmey (FR)', 46.6300, 7.1450, 'nature,adventure', 'Téléphérique ouvrant l''accès aux sentiers de randonnée et au panorama des Préalpes. Restauration en altitude.', 240, 3, false, true, ARRAY['Horaires restreints','Parking'], ARRAY['Été','Automne'], ARRAY['Famille','Amis','Couple'], 'fribourg', 'pending', false),
('Vallée du Petit Mont', 'Cerniat (FR)', 46.6480, 7.2050, 'nature', 'Vallée préservée idéale pour la randonnée familiale avec ses pâturages et sa chartreuse historique.', 240, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo','Couple'], 'fribourg', 'pending', false),

-- ───── MURTEN / MORAT & LAC DE MORAT ─────
('Vieille Ville de Morat', 'Murten (FR)', 46.9272, 7.1156, 'culture', 'Cité médiévale fortifiée avec ses remparts entièrement praticables, son château, ses arcades et son charme intemporel.', 120, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Promenade des Remparts Morat', 'Murten (FR)', 46.9277, 7.1160, 'culture,nature', 'Parcours unique sur les remparts médiévaux offrant une vue sur le lac et la vieille ville.', 60, 1, false, true, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Plage de Morat', 'Murten (FR)', 46.9275, 7.1100, 'nature,fun', 'Plage publique sur les rives du lac de Morat, idéale pour la baignade estivale et activités nautiques.', 240, 1, false, true, ARRAY['Parking'], ARRAY['Été'], ARRAY['Famille','Amis','Couple'], 'fribourg', 'pending', false),
('Croisière sur le Lac de Morat', 'Murten (FR)', 46.9270, 7.1145, 'nature,fun', 'Tour en bateau sur les trois lacs (Morat, Bienne, Neuchâtel) avec restauration à bord. Découverte des paysages lacustres.', 180, 4, false, true, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Famille','Amis'], 'fribourg', 'pending', false),
('Musée de Morat', 'Murten (FR)', 46.9275, 7.1140, 'culture', 'Musée régional dans un ancien moulin présentant l''histoire militaire et locale, notamment la bataille de Morat 1476.', 75, 2, true, false, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Solo','Couple'], 'fribourg', 'pending', false),
('Mont Vully', 'Sugiez (FR)', 46.9588, 7.0850, 'nature,gastronomy', 'Petite montagne entourée de vignobles produisant des vins de qualité, vue panoramique sur les trois lacs.', 180, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Amis','Famille'], 'fribourg', 'pending', false),
('Sentier de la Vue Vully', 'Praz-Vully (FR)', 46.9520, 7.0800, 'nature', 'Sentier panoramique reliant les villages viticoles du Vully avec vue imprenable sur le lac et les Alpes.', 180, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Caves du Vully - Dégustations', 'Praz-Vully (FR)', 46.9510, 7.0810, 'gastronomy', 'Visite de domaines vinicoles familiaux avec dégustation des vins du Vully (Chasselas, Pinot Noir).', 90, 3, true, false, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], 'fribourg', 'pending', false),

-- ───── ESTAVAYER & GLÂNE ─────
('Vieille Ville d''Estavayer-le-Lac', 'Estavayer-le-Lac (FR)', 46.8489, 6.8484, 'culture', 'Cité médiévale avec son château savoyard et son port de plaisance. Charme intemporel au bord du lac de Neuchâtel.', 120, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Musée des Grenouilles Estavayer', 'Estavayer-le-Lac (FR)', 46.8485, 6.8480, 'culture,fun', 'Musée insolite avec 108 grenouilles momifiées dans des scènes humaines, plus collections historiques et armes.', 60, 1, true, false, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis','Solo'], 'fribourg', 'pending', false),
('Plage d''Estavayer-le-Lac', 'Estavayer-le-Lac (FR)', 46.8500, 6.8500, 'nature,fun', 'Grande plage sablonneuse sur le lac de Neuchâtel, idéale pour la baignade et le farniente estival.', 240, 1, false, true, ARRAY['Parking'], ARRAY['Été'], ARRAY['Famille','Amis','Couple'], 'fribourg', 'pending', false),
('Aquaparc d''Estavayer', 'Estavayer-le-Lac (FR)', 46.8520, 6.8530, 'fun,sport', 'Parc aquatique gonflable géant sur le lac avec toboggans, trampolines et structures pour adultes et enfants.', 180, 4, false, true, ARRAY['Parking','Horaires restreints','Reservation necessaire'], ARRAY['Été'], ARRAY['Famille','Amis'], 'fribourg', 'pending', false),
('Château d''Oron', 'Oron (FR)', 46.5670, 6.8530, 'culture', 'Château bien préservé du XIIIe siècle abritant une bibliothèque historique exceptionnelle. À la frontière VD/FR.', 90, 2, true, true, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Romont - Cité du Vitrail', 'Romont (FR)', 46.6938, 6.9114, 'culture', 'Vieille cité dominée par son château abritant le Musée Suisse du Vitrail, collections d''art religieux uniques.', 120, 2, false, true, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),

-- ───── HAUTE-GRUYÈRE & PAYS-D'EN-HAUT FR ─────
('Lac Noir', 'Plaffeien (FR)', 46.6716, 7.2167, 'nature', 'Lac alpin entouré de forêts et de pâturages, sentier facile de 4km autour. Idéal toute saison.', 180, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Kaiseregg', 'Plaffeien (FR)', 46.6580, 7.2350, 'nature,adventure', 'Sommet préalpin (2185m) avec randonnée magnifique au départ du Lac Noir, vue 360° sur l''Oberland.', 360, 1, false, true, ARRAY['Parking'], ARRAY['Été','Automne'], ARRAY['Amis','Couple','Famille'], 'fribourg', 'pending', false),
('Berra', 'Cerniat (FR)', 46.6350, 7.2010, 'nature,adventure', 'Sommet alpin avec vue grandiose et restaurant d''altitude, parapente et randos pour tous niveaux.', 300, 1, false, true, ARRAY['Parking','Horaires restreints'], ARRAY['Été','Automne'], ARRAY['Amis','Couple','Solo'], 'fribourg', 'pending', false),
('Schwarzsee Centre de Loisirs', 'Plaffeien (FR)', 46.6720, 7.2140, 'sport,fun', 'Centre de loisirs au bord du Lac Noir avec piscine, mini-golf et pédalos. Idéal en famille.', 240, 3, true, true, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Amis'], 'fribourg', 'pending', false),
('Cabane du Lac Noir', 'Plaffeien (FR)', 46.6650, 7.2280, 'nature,gastronomy', 'Cabane d''altitude accessible en 1h30 de marche depuis le Lac Noir, fondue traditionnelle au coucher du soleil.', 360, 3, false, true, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Amis','Couple'], 'fribourg', 'pending', false),
('Bisses du Mont-Vully', 'Bellerive (FR)', 46.9530, 7.0830, 'nature', 'Anciens canaux d''irrigation suivis par un sentier botanique avec faune et flore locale.', 120, 1, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], 'fribourg', 'pending', false),
('Tour de Trême - Karting', 'La Tour-de-Trême (FR)', 46.6090, 7.0830, 'sport,fun', 'Piste de karting indoor et outdoor, accessible toute l''année. Sensations garanties pour groupes.', 60, 4, true, true, ARRAY['Parking','Reservation necessaire','Minimum de participants'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis','Famille'], 'fribourg', 'pending', false),

-- ───── SPÉCIALITÉS & GASTRO FRIBOURG ─────
('Restaurant le Chalet Gruyères', 'Gruyères (FR)', 46.5848, 7.0820, 'gastronomy', 'Spécialités fribourgeoises (fondue moitié-moitié, meringues à la double crème) dans un chalet authentique au pied du château.', 120, 4, true, false, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille','Amis'], 'fribourg', 'pending', false),
('Auberge de la Croix Blanche Posieux', 'Posieux (FR)', 46.7700, 7.1100, 'gastronomy', 'Auberge traditionnelle proposant les meilleures spécialités fribourgeoises, ambiance familiale.', 90, 3, true, false, ARRAY['Reservation necessaire','Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple'], 'fribourg', 'pending', false),
('Fromagerie d''Estavayer-le-Gibloux', 'Estavayer-le-Gibloux (FR)', 46.7400, 7.0250, 'gastronomy', 'Fromagerie artisanale produisant Gruyère AOP et autres spécialités, visite et boutique.', 60, 2, true, false, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Solo','Couple'], 'fribourg', 'pending', false),
('Marché de Bulle', 'Bulle (FR)', 46.6193, 7.0565, 'gastronomy,culture', 'Marché traditionnel hebdomadaire avec producteurs locaux, artisans et spécialités gruériennes.', 90, 1, false, true, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis'], 'fribourg', 'pending', false),
('Glacier du Mouret', 'Le Mouret (FR)', 46.7800, 7.2100, 'gastronomy,fun', 'Glaces artisanales aux saveurs originales (gentiane, foin, double crème), terrasse familiale.', 60, 2, false, true, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple'], 'fribourg', 'pending', false),
('Café Tivoli Châtel-St-Denis', 'Châtel-Saint-Denis (FR)', 46.5290, 6.9020, 'gastronomy', 'Restaurant historique avec terrasse vue sur la Vevyse, cuisine du terroir et carte de saison.', 120, 3, true, true, ARRAY['Reservation necessaire','Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Brunch à la Maison du Gruyère', 'Pringy-Gruyères (FR)', 46.5830, 7.0700, 'gastronomy', 'Brunch dominical avec spécialités fromagères et vue sur l''atelier de fabrication.', 120, 3, true, false, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], 'fribourg', 'pending', false),
('Cidrerie de la Mortigue', 'Saint-Aubin (FR)', 46.8870, 6.9090, 'gastronomy', 'Cidrerie artisanale avec dégustation de cidres et jus de pomme bio, boutique de produits du verger.', 60, 2, true, false, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Amis'], 'fribourg', 'pending', false);
