INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Canyoning Gorges du Chauderon', 'Montreux', 'adventure', 'Descente en rappel, sauts et toboggans naturels. Encadrement professionnel obligatoire.', 46.4208, 6.9097, 240, 5, ARRAY['Reservation necessaire','Minimum de participants'], ARRAY['Été','Automne'], ARRAY['Amis','Couple'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Canyoning Gorges du Chauderon' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Canyoning Gorges du Chauderon' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Parapente biplace Villars', 'Villars-sur-Ollon', 'adventure', 'Vol biplace de 15-30 min au-dessus des Alpes vaudoises. Vue Mont-Blanc + Dents du Midi.', 46.2972, 7.0481, 90, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Solo','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Parapente biplace Villars' AND location_name = 'Villars-sur-Ollon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Parapente biplace Villars' AND location_name = 'Villars-sur-Ollon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Via ferrata Tière', 'Évionnaz', 'adventure', 'Via ferrata difficile au-dessus du Trient. Pont himalayen et tyroliennes.', 46.1842, 7.0306, 240, 4, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Solo','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Via ferrata Tière' AND location_name = 'Évionnaz') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Via ferrata Tière' AND location_name = 'Évionnaz');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Acrobranche Aigle', 'Aigle', 'adventure', 'Parc de cordes dans la forêt. Parcours pour tous âges, tyroliennes géantes.', 46.3192, 6.97, 180, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Acrobranche Aigle' AND location_name = 'Aigle') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Acrobranche Aigle' AND location_name = 'Aigle');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Escape Room Lausanne Lock''d', 'Lausanne', 'adventure', 'Salles d''évasion thématiques. Énigmes corsées en équipe, 60 minutes pour s''échapper.', 46.5167, 6.63, 90, 3, ARRAY['Reservation necessaire','Minimum de participants'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis','Famille'], true, false, 'https://www.lockd.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Escape Room Lausanne Lock''d' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Escape Room Lausanne Lock''d' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Saut élastique Niouc', 'Vissoie', 'adventure', 'Saut depuis un pont à 190m de haut sur la rivière Navisence. Le plus haut saut élastique d''Europe.', 46.2336, 7.5694, 60, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Amis','Solo'], false, true, 'https://www.bungy.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Saut élastique Niouc' AND location_name = 'Vissoie') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Saut élastique Niouc' AND location_name = 'Vissoie');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Tyrolienne Champéry', 'Champéry', 'adventure', 'Tyrolienne géante de 2 km dans les Portes du Soleil. Vitesse jusqu''à 80 km/h.', 46.175, 6.8722, 30, 4, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Amis','Couple'], false, true, 'https://www.champery.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Tyrolienne Champéry' AND location_name = 'Champéry') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Tyrolienne Champéry' AND location_name = 'Champéry');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Rafting Sarine', 'Saanen', 'adventure', 'Descente en raft sur la Sarine sauvage. Plusieurs niveaux, encadrement pro.', 46.4953, 7.2606, 240, 4, ARRAY['Reservation necessaire','Minimum de participants'], ARRAY['Printemps','Été'], ARRAY['Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Rafting Sarine' AND location_name = 'Saanen') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Rafting Sarine' AND location_name = 'Saanen');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bains de Lavey', 'Lavey-les-Bains', 'relax', 'Source thermale la plus chaude de Suisse (62°C). Spa, bains intérieurs/extérieurs, soins.', 46.2056, 7.025, 240, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille','Solo'], true, true, 'https://www.lavey-les-bains.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bains de Lavey' AND location_name = 'Lavey-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bains de Lavey' AND location_name = 'Lavey-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Royal Plaza', 'Montreux', 'relax', 'Spa luxe avec piscine intérieure, sauna, hammam, soins. Vue sur le lac Léman.', 46.4308, 6.9117, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.royalplaza.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Royal Plaza' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Royal Plaza' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bains de Bex (Mines de sel)', 'Bex', 'relax', 'Centre de bien-être dans une ancienne mine. Piscines au sel, hammam de roche.', 46.2528, 7.0017, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Solo'], true, false, 'https://www.mines.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bains de Bex (Mines de sel)' AND location_name = 'Bex') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bains de Bex (Mines de sel)' AND location_name = 'Bex');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Yverdon-les-Bains thermes', 'Yverdon-les-Bains', 'relax', 'Centre thermal de référence : eaux sulfureuses à 28°C, spa, fitness, hôtel.', 46.7847, 6.6428, 240, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille','Solo'], true, true, 'https://www.cty.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Yverdon-les-Bains thermes' AND location_name = 'Yverdon-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Yverdon-les-Bains thermes' AND location_name = 'Yverdon-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Beau-Rivage Palace', 'Lausanne', 'relax', 'Spa cinq étoiles avec piscine intérieure, salle de cardio, soins haut de gamme.', 46.5097, 6.6361, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.brp.ch/fr/cinq-mondes-spa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Beau-Rivage Palace' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Beau-Rivage Palace' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Thermes des Salines de Bex', 'Bex', 'relax', 'Bains de saumure dans les anciennes mines de sel. Expérience unique sous terre.', 46.2444, 6.9883, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Solo'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Thermes des Salines de Bex' AND location_name = 'Bex') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Thermes des Salines de Bex' AND location_name = 'Bex');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Hôtel Villars Palace', 'Villars-sur-Ollon', 'relax', 'Spa de l''Alpine Lodge, cadre montagnard, soins après ski.', 46.2986, 7.0467, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.villarspalace.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Hôtel Villars Palace' AND location_name = 'Villars-sur-Ollon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Hôtel Villars Palace' AND location_name = 'Villars-sur-Ollon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Yoga Léman Vevey', 'Vevey', 'relax', 'Cours de yoga et méditation au bord du Léman, niveau débutant à avancé.', 46.4633, 6.8492, 90, 2, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Couple'], true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Yoga Léman Vevey' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Yoga Léman Vevey' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Le Signal de Bougy', 'Bougy-Villars', 'fun', 'Parc de loisirs avec animaux, mini-golf, places de jeux, restaurant. Vue Léman + Mont-Blanc.', 46.4628, 6.3258, 240, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Amis'], false, true, 'https://www.signaldebougy.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Le Signal de Bougy' AND location_name = 'Bougy-Villars') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Le Signal de Bougy' AND location_name = 'Bougy-Villars');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cinéma Open Air Lausanne', 'Lausanne', 'fun', 'Projections en plein air sur les bords du Léman, fin juillet. Films classiques et récents.', 46.5097, 6.6361, 180, 3, ARRAY['Horaires restreints'], ARRAY['Été'], ARRAY['Couple','Amis','Famille'], false, true, 'https://www.openair-cinema.ch', NULL, NULL, 'Juillet-août', 'July-August', NULL, NULL, 'seasonal', ARRAY[7,8]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cinéma Open Air Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cinéma Open Air Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Mini-golf Vidy', 'Lausanne', 'fun', 'Parcours 18 trous au bord du Léman, dans le parc de Vidy. Idéal famille.', 46.5172, 6.5917, 90, 2, ARRAY[]::text[], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Amis','Couple'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[4,5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Mini-golf Vidy' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Mini-golf Vidy' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bowling Vevey', 'Vevey', 'fun', 'Bowling moderne avec 12 pistes, billard, restaurant. Animations le weekend.', 46.4633, 6.8472, 120, 3, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis','Famille','Couple'], true, false, 'https://www.bowlingvevey.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bowling Vevey' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bowling Vevey' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Magic Casino Crissier', 'Crissier', 'fun', 'Casino moderne, machines à sous, jeux de table. Restaurant et bar.', 46.5497, 6.5775, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Magic Casino Crissier' AND location_name = 'Crissier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Magic Casino Crissier' AND location_name = 'Crissier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Festival de la Cité', 'Lausanne', 'event', 'Festival pluridisciplinaire gratuit en juillet : musique, théâtre, danse dans la vieille ville.', 46.5228, 6.6353, 240, 1, ARRAY[]::text[], ARRAY['Été'], ARRAY['Famille','Amis','Couple','Solo'], false, true, 'https://www.festivalcite.ch', NULL, NULL, 'Début juillet 2026', 'Early July 2026', '2026-07-07'::date, '2026-07-12'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Festival de la Cité' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Festival de la Cité' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cully Jazz Festival', 'Cully', 'event', 'Festival de jazz historique en avril. Concerts dans 3 caveaux + scènes off gratuites.', 46.49, 6.73, 240, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps'], ARRAY['Couple','Amis','Solo'], false, true, 'https://www.cullyjazz.ch', NULL, NULL, 'Avril 2026', 'April 2026', '2026-04-10'::date, '2026-04-18'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cully Jazz Festival' AND location_name = 'Cully') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cully Jazz Festival' AND location_name = 'Cully');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Marché de Noël de Montreux', 'Montreux', 'event', 'Plus grand marché de Noël de Suisse romande sur les quais. Père Noël en tyrolienne au-dessus du lac.', 46.4308, 6.9117, 180, 2, ARRAY['Parking'], ARRAY['Hiver'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.montreuxnoel.com', NULL, NULL, '20 nov - 24 déc 2026', '20 Nov - 24 Dec 2026', '2026-11-20'::date, '2026-12-24'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Marché de Noël de Montreux' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Marché de Noël de Montreux' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Brandons d''Yverdon', 'Yverdon-les-Bains', 'event', 'Carnaval avec cortèges, Guggenmusiks, bal masqué. Plus de 100 ans de tradition.', 46.7783, 6.6406, 240, 1, ARRAY['Parking'], ARRAY['Printemps'], ARRAY['Famille','Amis'], false, true, 'https://www.brandons-yverdon.ch', NULL, NULL, 'Mi-mars 2026', 'Mid-March 2026', '2026-03-13'::date, '2026-03-15'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Brandons d''Yverdon' AND location_name = 'Yverdon-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Brandons d''Yverdon' AND location_name = 'Yverdon-les-Bains');
