INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Glacier Express', 'Zermatt', 'fun', 'Train panoramique de prestige Zermatt-Saint-Moritz, ''le train rapide le plus lent du monde'' (8h, 91 tunnels, 291 ponts).', 46.0207, 7.7491, 480, 5, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.glacierexpress.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Glacier Express' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Glacier Express' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Funiculaire Saint-Luc-Tignousa', 'Saint-Luc', 'fun', 'Funiculaire vers Tignousa (2''200m), point de depart du chemin des planetes. Vue 4000m valaisans.', 46.2178, 7.6122, 60, 3, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.funiluc.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Funiculaire Saint-Luc-Tignousa' AND location_name = 'Saint-Luc') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Funiculaire Saint-Luc-Tignousa' AND location_name = 'Saint-Luc');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Funiculaire Crans-Cry d''Er', 'Crans-Montana', 'fun', 'Telecabine de Crans-Montana au sommet de Cry d''Er (2''267m). Restaurant panoramique, depart de randonnees.', 46.3117, 7.4853, 60, 4, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.crans-montana.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Funiculaire Crans-Cry d''Er' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Funiculaire Crans-Cry d''Er' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Karting Châteauneuf-Conthey', 'Châteauneuf-Conthey', 'fun', 'Piste de karting indoor en plaine du Rhone. Karts puissants, championnat, ideal pour tous niveaux.', 46.2167, 7.3083, 90, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis','Famille'], true, false, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Karting Châteauneuf-Conthey' AND location_name = 'Châteauneuf-Conthey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Karting Châteauneuf-Conthey' AND location_name = 'Châteauneuf-Conthey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Mountain Cart Verbier', 'Verbier', 'fun', 'Descente en chariots de montagne sur 4 km depuis La Chaux. Sensations, vue Combin, accessible des 7 ans.', 46.0961, 7.2286, 60, 4, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille','Amis'], false, true, 'https://www.verbier.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Mountain Cart Verbier' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Mountain Cart Verbier' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Mountain Cart Crans-Montana', 'Crans-Montana', 'fun', 'Descente en mountain cart depuis Cry d''Er. Karts bridés pour les enfants, sensations garanties.', 46.3117, 7.4853, 60, 4, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille','Amis'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Mountain Cart Crans-Montana' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Mountain Cart Crans-Montana' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Trottinette tout-terrain Saas-Fee', 'Saas-Fee', 'fun', 'Descente en trottinette VTT depuis Hannig (2''350m) vers le village. 7 km de fun garanti.', 46.1086, 7.9272, 60, 3, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille','Amis'], false, true, 'https://www.saas-fee.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Trottinette tout-terrain Saas-Fee' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Trottinette tout-terrain Saas-Fee' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Trottinette Crans-Montana', 'Crans-Montana', 'fun', 'Descente en trottinette tout-terrain depuis Cry d''Er. Plusieurs parcours selon niveau.', 46.3117, 7.4853, 60, 3, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille','Amis'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Trottinette Crans-Montana' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Trottinette Crans-Montana' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Trottinette Champéry', 'Champéry', 'fun', 'Descente en trottinette tout-terrain depuis Croix-de-Culet vers Champery. 1100m de denivele negatif.', 46.175, 6.8722, 60, 3, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille','Amis'], false, true, 'https://www.champery.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Trottinette Champéry' AND location_name = 'Champéry') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Trottinette Champéry' AND location_name = 'Champéry');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cinéma Capitole Sion', 'Sion', 'fun', 'Cinéma historique au cœur de Sion. 6 salles, programmation grand public et art-et-essai.', 46.2306, 7.3603, 120, 3, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis','Solo'], true, false, 'https://www.cinemas-sion.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cinéma Capitole Sion' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cinéma Capitole Sion' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cinéma Lux Sion', 'Sion', 'fun', 'Cinéma de quartier de Sion. Programmation art-et-essai, films d''auteur, films suisses en VO.', 46.2306, 7.3603, 120, 3, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Couple','Amis'], true, false, 'https://www.cinemas-sion.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cinéma Lux Sion' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cinéma Lux Sion' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bowling Sion', 'Sion', 'fun', 'Centre de bowling moderne a Sion. 10 pistes, billard, snack-bar, tournois reguliers.', 46.2306, 7.3603, 90, 3, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis','Couple'], true, false, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bowling Sion' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bowling Sion' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bowling Sierre', 'Sierre', 'fun', 'Centre de bowling de Sierre. 8 pistes, restaurant, ideal pour soirees entre amis.', 46.2917, 7.5333, 90, 3, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis','Couple'], true, false, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bowling Sierre' AND location_name = 'Sierre') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bowling Sierre' AND location_name = 'Sierre');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Casino de Crans-Montana', 'Crans-Montana', 'fun', 'Casino de la station de Crans. Machines a sous, jeux de table, restaurant, evenements.', 46.3117, 7.4853, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.casinodecrans.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Casino de Crans-Montana' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Casino de Crans-Montana' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Casino de Saxon', 'Saxon', 'fun', 'Plus ancien casino du Valais (1856). Machines a sous, jeux de table, ambiance retro.', 46.15, 7.175, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.casinodesaxon.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Casino de Saxon' AND location_name = 'Saxon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Casino de Saxon' AND location_name = 'Saxon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Téléphérique Saas-Almagell-Heidbodme', 'Saas-Almagell', 'fun', 'Telecabine entre Saas-Almagell et Heidbodme (2''400m). Acces randos, panorama 4000m.', 46.0944, 7.9583, 60, 3, ARRAY['Parking','Horaires restreints'], ARRAY['Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.saas-almagell.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Téléphérique Saas-Almagell-Heidbodme' AND location_name = 'Saas-Almagell') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Téléphérique Saas-Almagell-Heidbodme' AND location_name = 'Saas-Almagell');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Tubing Saas-Fee Spielboden', 'Saas-Fee', 'fun', 'Piste de tubing en hiver a Spielboden. Descente en bouée gonflable sur 100m de denivele, fun garanti.', 46.1086, 7.9272, 60, 3, ARRAY['Reservation necessaire'], ARRAY['Hiver'], ARRAY['Famille','Amis'], false, true, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[12,1,2,3]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Tubing Saas-Fee Spielboden' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Tubing Saas-Fee Spielboden' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Gravity Park Saas-Fee', 'Saas-Fee', 'fun', 'Snowpark international au glacier de Saas-Fee. 25+ kickers, rails, half-pipe. Open ete et hiver.', 46.1086, 7.9272, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Été','Automne','Hiver'], ARRAY['Amis','Solo'], false, true, 'https://www.saas-fee.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Gravity Park Saas-Fee' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Gravity Park Saas-Fee' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Marché de Sion', 'Sion', 'fun', 'Marche traditionnel sur la rue du Grand-Pont (vendredis et samedis). Produits valaisans, ambiance medievale.', 46.2306, 7.3603, 90, 1, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, 'weekly', NULL, ARRAY[5,6]::int[], 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Marché de Sion' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Marché de Sion' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Marché de Martigny', 'Martigny', 'fun', 'Marche du jeudi place Centrale. Produits du terroir valaisan, vins, fromages, animations.', 46.1011, 7.075, 90, 1, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, 'loc_lower', NULL, NULL, NULL, NULL, 'weekly', NULL, ARRAY[4]::int[], 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Marché de Martigny' AND location_name = 'Martigny') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Marché de Martigny' AND location_name = 'Martigny');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Saint-Bernard Express', 'Orsières', 'fun', 'Train touristique du Saint-Bernard Express, dessert le Pays du Saint-Bernard (Champex, La Fouly, Bourg-Saint-Pierre).', 46.0306, 7.1481, 90, 3, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], true, false, 'https://www.tmrsa.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Saint-Bernard Express' AND location_name = 'Orsières') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Saint-Bernard Express' AND location_name = 'Orsières');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Funi-Park Saint-Luc', 'Saint-Luc', 'fun', 'Parc de jeux et de detente au sommet du funiculaire de Saint-Luc. Tyrolienne, parcours aventure, restaurant.', 46.2178, 7.6122, 180, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Funi-Park Saint-Luc' AND location_name = 'Saint-Luc') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Funi-Park Saint-Luc' AND location_name = 'Saint-Luc');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Brigerbad Wasserspielpark', 'Brig-Glis', 'fun', 'Parc aquatique enfants des Bains de Brigerbad. Toboggans thermaux, rivière sauvage, châteaux d''eau.', 46.3056, 7.9694, 240, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille'], false, true, 'https://www.thermalbad-brigerbad.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Brigerbad Wasserspielpark' AND location_name = 'Brig-Glis') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Brigerbad Wasserspielpark' AND location_name = 'Brig-Glis');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Espace Mont-Cervin Findeln', 'Findeln', 'fun', 'Hameau alpin a 2''130m face au Cervin. Restaurants etagés sur la pente, ambiance unique entre les melezes.', 45.9961, 7.76, 180, 3, ARRAY['Reservation necessaire'], ARRAY['Été','Hiver'], ARRAY['Couple','Famille','Amis'], false, true, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Espace Mont-Cervin Findeln' AND location_name = 'Findeln') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Espace Mont-Cervin Findeln' AND location_name = 'Findeln');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Marché de Brigue (Manor)', 'Brigue', 'fun', 'Marche hebdomadaire de Brigue, en alemanique, produits du Haut-Valais : pain de seigle AOP, viande sechee, vin Heida.', 46.3167, 7.9833, 90, 1, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'weekly', NULL, ARRAY[4]::int[], 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Marché de Brigue (Manor)' AND location_name = 'Brigue') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Marché de Brigue (Manor)' AND location_name = 'Brigue');
