INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Tour de Sauvabelin', 'Lausanne', 'nature', 'Tour en bois de 35m offrant une vue 360° sur Lausanne, le Léman et les Alpes. Ascension gratuite par escalier en colimaçon.', 46.54, 6.65, 60, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo','Amis'], false, true, 'https://www.lausanne.ch/officiel/administration/sports-et-cohesion-sociale/service-des-parcs-et-domaines/parcs-promenades/tour-de-sauvabelin.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Tour de Sauvabelin' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Tour de Sauvabelin' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Lavaux Vinorama', 'Rivaz', 'nature', 'Centre de découverte des vins de Lavaux, classés UNESCO. Dégustation de 290 vins issus de 165 vignerons.', 46.4794, 6.7717, 90, 3, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Amis'], true, false, 'https://www.lavaux-vinorama.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Lavaux Vinorama' AND location_name = 'Rivaz') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Lavaux Vinorama' AND location_name = 'Rivaz');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Sentier des Vignerons Lavaux', 'Lutry', 'nature', 'Randonnée de 11 km à travers les terrasses viticoles UNESCO, de Lutry à Saint-Saphorin. Vues spectaculaires sur le Léman.', 46.5042, 6.6856, 240, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Famille','Amis'], false, true, 'https://www.montreuxriviera.com/fr/P38019/sentier-des-vignerons', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Sentier des Vignerons Lavaux' AND location_name = 'Lutry') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Sentier des Vignerons Lavaux' AND location_name = 'Lutry');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Rochers-de-Naye', 'Montreux', 'nature', 'Sommet à 2042m accessible en train à crémaillère depuis Montreux. Marmottes paradise, vue Léman + Alpes.', 46.4286, 6.9764, 240, 4, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Été','Automne'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.goldenpass.ch/fr/excursions/rochers-de-naye', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Rochers-de-Naye' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Rochers-de-Naye' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Lac de Bret', 'Puidoux', 'nature', 'Petit lac glaciaire entouré de forêts. Sentier pédestre 3 km, baignade interdite mais idéal pour pique-nique.', 46.5208, 6.8044, 90, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Lac de Bret' AND location_name = 'Puidoux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Lac de Bret' AND location_name = 'Puidoux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Mont Pèlerin', 'Chardonne', 'nature', 'Funiculaire vers ce sommet de 1080m. Vue panoramique sur le Léman, Plein Ciel restaurant au sommet.', 46.4769, 6.8597, 120, 3, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], false, true, 'https://www.mob.ch/lignes-train/funiculaire-vevey-mont-pelerin/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Mont Pèlerin' AND location_name = 'Chardonne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Mont Pèlerin' AND location_name = 'Chardonne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bois du Jorat', 'Lausanne', 'nature', 'Forêt de 25 km² au nord de Lausanne avec sentiers balisés, parcours VTT et points de vue. Idéal pour la déconnexion.', 46.5778, 6.6694, 180, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bois du Jorat' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bois du Jorat' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Lac de Joux', 'Le Pont', 'nature', 'Plus grand lac du Jura. Baignade en été, ski de fond et patin à glace l''hiver. Vue spectaculaire sur les sommets.', 46.6722, 6.3278, 240, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.myvalleedejoux.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Lac de Joux' AND location_name = 'Le Pont') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Lac de Joux' AND location_name = 'Le Pont');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Réserve naturelle des Grangettes', 'Noville', 'nature', 'Plus grande zone humide de Suisse romande. 330 ha de roselières, observation des oiseaux migrateurs.', 46.3833, 6.8667, 180, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo','Couple'], false, true, 'https://www.grangettes.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Réserve naturelle des Grangettes' AND location_name = 'Noville') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Réserve naturelle des Grangettes' AND location_name = 'Noville');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Glacier 3000', 'Les Diablerets', 'nature', 'Glacier accessible en téléphérique, peak walk by Tissot (pont suspendu entre 2 sommets). Vue Mont-Blanc + Cervin.', 46.3556, 7.2125, 240, 5, ARRAY['Parking','Reservation necessaire'], ARRAY['Été','Automne','Hiver'], ARRAY['Couple','Amis','Famille'], false, true, 'https://www.glacier3000.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Glacier 3000' AND location_name = 'Les Diablerets') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Glacier 3000' AND location_name = 'Les Diablerets');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Mont Tendre', 'Vallée de Joux', 'nature', 'Plus haut sommet du Jura suisse (1679m). Randonnée de 4h depuis Le Pont, panorama exceptionnel sur les Alpes.', 46.6017, 6.3186, 360, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Solo','Amis','Couple'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Mont Tendre' AND location_name = 'Vallée de Joux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Mont Tendre' AND location_name = 'Vallée de Joux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bois de Chênes', 'Genolier', 'nature', 'Réserve naturelle avec une chênaie centenaire. Sentier didactique de 2h sur les arbres et la biodiversité.', 46.4456, 6.2306, 120, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bois de Chênes' AND location_name = 'Genolier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bois de Chênes' AND location_name = 'Genolier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Plage de Préverenges', 'Préverenges', 'nature', 'Plage de sable au bord du Léman, vue Mont-Blanc. Lieu de migration des oiseaux. Baignade et pique-nique.', 46.5092, 6.5269, 120, 1, ARRAY['Parking'], ARRAY['Printemps','Été'], ARRAY['Famille','Couple','Amis'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Plage de Préverenges' AND location_name = 'Préverenges') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Plage de Préverenges' AND location_name = 'Préverenges');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Tour d''Aï', 'Leysin', 'nature', 'Sommet rocheux de 2331m au-dessus de Leysin. Randonnée alpine technique avec vue Dents du Midi + Mont-Blanc.', 46.3517, 7.0153, 360, 1, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Solo','Amis','Couple'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Tour d''Aï' AND location_name = 'Leysin') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Tour d''Aï' AND location_name = 'Leysin');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Forêt du Risoud', 'Vallée de Joux', 'nature', 'Plus grande forêt continue de Suisse, célèbre pour son bois de résonance utilisé en lutherie. Sentier des géants.', 46.6444, 6.2944, 180, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo','Couple'], false, true, 'https://www.myvalleedejoux.ch/fr/N1410/le-risoud', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Forêt du Risoud' AND location_name = 'Vallée de Joux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Forêt du Risoud' AND location_name = 'Vallée de Joux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée Olympique', 'Lausanne', 'culture', 'Musée incontournable des Jeux Olympiques. Collections, films, expositions interactives. Note Google : 4.6/5.', 46.5078, 6.6336, 180, 4, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo','Amis'], true, false, 'https://olympics.com/musee', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée Olympique' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée Olympique' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cathédrale Notre-Dame de Lausanne', 'Lausanne', 'culture', 'Joyau gothique du XIIIe siècle. Le veilleur de nuit crie chaque heure de 22h à 2h. Tours offrant vue panoramique.', 46.5228, 6.6353, 90, 1, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Solo','Famille'], true, false, 'https://www.cathedrale-lausanne.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cathédrale Notre-Dame de Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cathédrale Notre-Dame de Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Plateforme 10', 'Lausanne', 'culture', 'Pôle muséal regroupant MCBA, Photo Élysée et mudac. Collections d''art contemporain et photographie.', 46.5169, 6.6294, 180, 4, ARRAY['Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Solo','Amis'], true, false, 'https://plateforme10.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Plateforme 10' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Plateforme 10' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Château de Chillon', 'Veytaux', 'culture', 'Château médiéval sur le Léman, plus visité de Suisse. Forteresse savoyarde du XIIIe siècle. 4.6/5 sur Google.', 46.4144, 6.9275, 150, 3, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo','Amis'], true, false, 'https://www.chillon.ch', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Chillon_Castle.jpg/1280px-Chillon_Castle.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Château de Chillon' AND location_name = 'Veytaux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Château de Chillon' AND location_name = 'Veytaux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Chaplin''s World', 'Corsier-sur-Vevey', 'culture', 'Musée immersif dédié à Charlie Chaplin dans son ancienne demeure. Studios reconstitués. Note 4.5/5.', 46.4847, 6.8633, 180, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo','Amis'], true, false, 'https://www.chaplinsworld.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Chaplin''s World' AND location_name = 'Corsier-sur-Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Chaplin''s World' AND location_name = 'Corsier-sur-Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Alimentarium', 'Vevey', 'culture', 'Premier musée au monde consacré à l''alimentation. Expositions interactives, cours de cuisine.', 46.4647, 6.8472, 150, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Solo','Couple'], true, false, 'https://www.alimentarium.org', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Alimentarium' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Alimentarium' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée suisse du jeu', 'La Tour-de-Peilz', 'culture', 'Au château de La Tour-de-Peilz : 700 jeux du monde entier, possibilité d''y jouer. Idéal famille.', 46.4575, 6.8589, 120, 2, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Amis'], true, false, 'https://www.museedujeu.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée suisse du jeu' AND location_name = 'La Tour-de-Peilz') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée suisse du jeu' AND location_name = 'La Tour-de-Peilz');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Site romain d''Avenches', 'Avenches', 'culture', 'Ancienne capitale de l''Helvétie romaine. Théâtre antique, amphithéâtre, musée romain. Site UNESCO en lice.', 46.8819, 7.0431, 180, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo','Couple'], false, true, 'https://www.aventicum.org', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Site romain d''Avenches' AND location_name = 'Avenches') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Site romain d''Avenches' AND location_name = 'Avenches');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Château de Grandson', 'Grandson', 'culture', 'Forteresse médiévale du XIe siècle. Salle des chevaliers, expositions sur la bataille de 1476.', 46.8128, 6.6433, 90, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], true, false, 'https://www.chateau-grandson.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Château de Grandson' AND location_name = 'Grandson') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Château de Grandson' AND location_name = 'Grandson');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Château d''Aigle (Musée du vin)', 'Aigle', 'culture', 'Château du XIIe siècle abritant le Musée de la vigne et du vin. Dégustations possibles.', 46.3192, 6.9697, 120, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Solo','Amis'], true, false, 'https://www.chateauaigle.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Château d''Aigle (Musée du vin)' AND location_name = 'Aigle') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Aigle' AND location_name = 'Aigle');
