INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Le Mirador Resort & Spa', 'Mont-Pèlerin', 'relax', 'Hotel 5* avec spa Givenchy panoramique sur le Leman. Piscines, soins haut de gamme, vue Alpes.', 46.4769, 6.8597, 240, 5, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.mirador.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Le Mirador Resort & Spa' AND location_name = 'Mont-Pèlerin') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Le Mirador Resort & Spa' AND location_name = 'Mont-Pèlerin');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Royal Savoy', 'Lausanne', 'relax', 'Spa 5* du Royal Savoy Hotel. Piscine inox, sauna fumant, hammam, soins signature, hammam oriental.', 46.5097, 6.6336, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.royalsavoy.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Royal Savoy' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Royal Savoy' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Lausanne Palace', 'Lausanne', 'relax', 'Spa CinqMondes du Lausanne Palace 5*. Piscine, sauna, hammam, soins signature inspires d''Asie.', 46.5193, 6.6293, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.lausanne-palace.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Lausanne Palace' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Lausanne Palace' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Mövenpick Lausanne', 'Lausanne', 'relax', 'Spa de l''hotel Movenpick a Ouchy. Piscine interieure, sauna, hammam, fitness, vue lac.', 46.5106, 6.6389, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.movenpick.com/lausanne', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Mövenpick Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Mövenpick Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Mirabeau Lausanne', 'Lausanne', 'relax', 'Spa boutique 4* a Lausanne, sauna, soins corps, hammam, ambiance feutree.', 46.5189, 6.6286, 120, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.mirabeau.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Mirabeau Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Mirabeau Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Continental Lausanne', 'Lausanne', 'relax', 'Spa de l''hotel Continental, en gare. Soins du visage, du corps, sauna et hammam.', 46.5167, 6.6294, 120, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Solo'], true, false, 'https://www.continentalhotel.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Continental Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Continental Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Carlton Lausanne', 'Lausanne', 'relax', 'Spa 4* de l''hotel Carlton. Sauna, hammam, soins, ambiance art-deco.', 46.5125, 6.6355, 120, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.carltonlausanne.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Carlton Lausanne' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Carlton Lausanne' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa La Reserve Eden au Lac', 'Lausanne', 'relax', 'Spa du Reserve Eden au Lac (Bellerive). Piscine indoor, jardin, soins haut de gamme face au Leman.', 46.5072, 6.645, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa La Reserve Eden au Lac' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa La Reserve Eden au Lac' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Puressens Spa Trois Couronnes', 'Vevey', 'relax', 'Spa 5* de l''hotel des Trois Couronnes (1842). Piscine vue lac, hammam, soins exclusifs Cinq Mondes.', 46.4617, 6.8478, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.hoteltroiscouronnes.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Puressens Spa Trois Couronnes' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Puressens Spa Trois Couronnes' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Grand Hôtel du Lac Vevey', 'Vevey', 'relax', 'Spa 5* Relais & Châteaux. Piscine, hammam, soins corps et visage, jardin classe au bord du Leman.', 46.4658, 6.84, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.grandhoteldulac.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Grand Hôtel du Lac Vevey' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Grand Hôtel du Lac Vevey' AND location_name = 'Vevey');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Modern Times Hotel', 'Chexbres', 'relax', 'Spa 4* a Chexbres, vue panoramique sur Lavaux. Piscine, sauna, hammam, soins.', 46.4842, 6.7917, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.moderntimeshotel.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Modern Times Hotel' AND location_name = 'Chexbres') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Modern Times Hotel' AND location_name = 'Chexbres');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Willow Stream Spa Fairmont', 'Montreux', 'relax', 'Spa du Fairmont Le Montreux Palace 5*. Piscine vue lac, sauna, hammam, soins signature.', 46.4337, 6.9111, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.fairmont.com/montreux', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Willow Stream Spa Fairmont' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Willow Stream Spa Fairmont' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Eden Palace au Lac', 'Montreux', 'relax', 'Spa de l''hotel Eden Palace au Lac (4*+). Piscine, sauna, hammam, soins, terrasse face au Leman.', 46.4318, 6.9117, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.edenpalace.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Eden Palace au Lac' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Eden Palace au Lac' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Eastwest Hotel', 'Montreux', 'relax', 'Spa boutique de l''hotel Eastwest 5*. Soins signatures asiatiques, hammam, ambiance feutree.', 46.4337, 6.9119, 120, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.eastwest.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Eastwest Hotel' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Eastwest Hotel' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Suisse-Majestic', 'Montreux', 'relax', 'Petit spa du Grand Hotel Suisse-Majestic. Piscine, sauna, hammam, vue lac.', 46.4339, 6.9119, 120, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.suisse-majestic.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Suisse-Majestic' AND location_name = 'Montreux') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Suisse-Majestic' AND location_name = 'Montreux');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Hôtel RoyAlp Spa Villars', 'Villars-sur-Ollon', 'relax', 'Spa 5* du Hôtel RoyAlp. Piscine intérieure-extérieure chauffée, sauna, hammam, vue Alpes.', 46.2986, 7.0467, 240, 5, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, true, 'https://www.royalp.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Hôtel RoyAlp Spa Villars' AND location_name = 'Villars-sur-Ollon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Hôtel RoyAlp Spa Villars' AND location_name = 'Villars-sur-Ollon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Bristol Villars', 'Villars-sur-Ollon', 'relax', 'Spa de l''hotel Bristol 4*+. Piscine vue Dents du Midi, sauna finlandais, hammam, soins.', 46.2986, 7.047, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.bristol-villars.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Bristol Villars' AND location_name = 'Villars-sur-Ollon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Bristol Villars' AND location_name = 'Villars-sur-Ollon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Eurotel Victoria Villars', 'Villars-sur-Ollon', 'relax', 'Spa de l''Eurotel Victoria 4*. Piscine, sauna, hammam, soins, ambiance familiale alpine.', 46.298, 7.0461, 150, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.eurotel-victoria.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Eurotel Victoria Villars' AND location_name = 'Villars-sur-Ollon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Eurotel Victoria Villars' AND location_name = 'Villars-sur-Ollon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Hôtel Christiania', 'Leysin', 'relax', 'Petit spa de l''Hotel Christiania. Sauna, jacuzzi, vue Dents du Midi, ambiance chalet.', 46.3478, 7.0089, 120, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, true, 'https://www.christiania-leysin.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Hôtel Christiania' AND location_name = 'Leysin') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Hôtel Christiania' AND location_name = 'Leysin');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Hôtel La Prairie Yverdon', 'Yverdon-les-Bains', 'relax', 'Spa de l''hotel 4* La Prairie. Soins haut de gamme, jacuzzi, hammam, complementaire aux Bains thermaux.', 46.7847, 6.6428, 150, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.laprairiehotel.ch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Hôtel La Prairie Yverdon' AND location_name = 'Yverdon-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Hôtel La Prairie Yverdon' AND location_name = 'Yverdon-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Croisière sunset CGN Léman', 'Lausanne-Ouchy', 'relax', 'Croisière au coucher de soleil sur le Léman, 1h30 a bord d''un bateau Belle Epoque CGN. Apéro panoramique.', 46.5083, 6.6261, 90, 3, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Famille','Amis'], true, true, 'https://www.cgn.ch', NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[4,5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Croisière sunset CGN Léman' AND location_name = 'Lausanne-Ouchy') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Croisière sunset CGN Léman' AND location_name = 'Lausanne-Ouchy');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Sentier des Sens Sauvabelin', 'Lausanne', 'relax', 'Sentier didactique en boucle dans la foret de Sauvabelin. Forest bathing au-dessus de Lausanne, ideal pour decompresser.', 46.54, 6.65, 90, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Sentier des Sens Sauvabelin' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Sentier des Sens Sauvabelin' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Plage relax de Cully', 'Cully', 'relax', 'Petite plage de galets en plein cœur de Lavaux UNESCO. Baignade calme, vue vignes et lac, idéal pour bouquiner.', 46.49, 6.7333, 120, 1, ARRAY[]::text[], ARRAY['Printemps','Été'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Plage relax de Cully' AND location_name = 'Cully') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Plage relax de Cully' AND location_name = 'Cully');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Centre Yoga Sereynité', 'Lausanne', 'relax', 'Studio de yoga de reference a Lausanne. Cours hatha, vinyasa, yin, ateliers meditation. Tous niveaux.', 46.5197, 6.6328, 90, 2, ARRAY['Reservation necessaire','Horaires restreints'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Couple'], true, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Centre Yoga Sereynité' AND location_name = 'Lausanne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Centre Yoga Sereynité' AND location_name = 'Lausanne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Promenade des Quais Vevey-Montreux', 'Vevey', 'relax', 'Promenade lacustre de 7 km le long du Leman, de Vevey a Montreux. Plage, sculptures, kiosques, sereinité.', 46.4633, 6.8492, 120, 1, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Promenade des Quais Vevey-Montreux' AND location_name = 'Vevey') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Promenade des Quais Vevey-Montreux' AND location_name = 'Vevey');
