INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Mines de Bagnes', 'Le Châble', 'culture', 'Mines de cuivre exploitées pendant 200 ans. Visite guidée souterraine, casque obligatoire.', 46.0647, 7.2125, 120, 3, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.mines.bagnes.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Mines de Bagnes' AND location_name = 'Le Châble') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Mines de Bagnes' AND location_name = 'Le Châble');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Stockalperschloss', 'Brig', 'culture', 'Plus grand château privé baroque de Suisse (XVIIe), bâti par le ''roi du Simplon''.', 46.3167, 7.9833, 120, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], true, false, 'https://www.brig-simplon.ch/stockalperschloss', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Stockalperschloss' AND location_name = 'Brig') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Stockalperschloss' AND location_name = 'Brig');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Église de Rarogne', 'Raron', 'culture', 'Église perchée sur un piton rocheux. Tombe de Rilke. Vue spectaculaire.', 46.3083, 7.8, 60, 1, ARRAY[]::text[], ARRAY['Printemps','Été','Automne'], ARRAY['Solo','Couple'], true, false, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Église de Rarogne' AND location_name = 'Raron') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Église de Rarogne' AND location_name = 'Raron');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée Suisse de Spéléologie', 'Chamoson', 'culture', 'Tout sur les grottes : géologie, faune cavernicole, équipements. Unique en Suisse.', 46.2042, 7.2256, 90, 2, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Solo'], true, false, 'https://www.museespeleo.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée Suisse de Spéléologie' AND location_name = 'Chamoson') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée Suisse de Spéléologie' AND location_name = 'Chamoson');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Tibetisches Klosterhaus', 'Visp', 'culture', 'Petit temple bouddhiste, le seul du Valais. Visite et méditation possibles.', 46.2944, 7.8806, 60, 1, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Couple'], true, false, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Tibetisches Klosterhaus' AND location_name = 'Visp') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Tibetisches Klosterhaus' AND location_name = 'Visp');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Damien Germanier', 'Sion', 'gastronomy', 'Restaurant gastronomique 1 étoile Michelin. Cuisine valaisanne créative, produits locaux.', 46.2306, 7.3592, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.damiengermanier.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Damien Germanier' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Damien Germanier' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Caves Provins', 'Sion', 'gastronomy', 'Plus grande cave coopérative de Suisse. Visite + dégustation de Petite Arvine, Cornalin, Humagne.', 46.2297, 7.3686, 90, 2, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.provins.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Caves Provins' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Caves Provins' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Château de Villa', 'Sierre', 'gastronomy', 'Restaurant gastronomique dans un château renaissance. Cuisine valaisanne moderne.', 46.2917, 7.5333, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.chateaudevilla.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Château de Villa' AND location_name = 'Sierre') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Château de Villa' AND location_name = 'Sierre');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Le Mille Sens', 'Sion', 'gastronomy', 'Bistro de quartier réputé, cuisine du marché. Très bon rapport qualité-prix.', 46.2333, 7.3611, 120, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis','Famille'], true, false, 'https://www.lemillesens.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Le Mille Sens' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Le Mille Sens' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Heida Visperterminen', 'Visperterminen', 'gastronomy', 'Plus haute vigne d''Europe (1100m). Dégustation Heida (Païen) avec vue spectaculaire.', 46.2683, 7.8839, 120, 3, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Amis'], false, true, 'https://www.stjodernkellerei.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Heida Visperterminen' AND location_name = 'Visperterminen') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Heida Visperterminen' AND location_name = 'Visperterminen');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Domaine du Mont d''Or', 'Pont-de-la-Morge', 'gastronomy', 'Domaine viticole historique. Cave creusée dans la roche. Dégustations et visites.', 46.22, 7.3, 90, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Amis'], true, false, 'https://www.montdor-wine.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Domaine du Mont d''Or' AND location_name = 'Pont-de-la-Morge') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Domaine du Mont d''Or' AND location_name = 'Pont-de-la-Morge');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Restaurant Schloss Leuk', 'Leuk', 'gastronomy', 'Restaurant gastronomique dans un château. Cuisine méditerranéenne raffinée.', 46.3144, 7.6342, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple'], true, false, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Restaurant Schloss Leuk' AND location_name = 'Leuk') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Restaurant Schloss Leuk' AND location_name = 'Leuk');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Brasserie Valaisanne', 'Sion', 'gastronomy', 'Brasserie historique du Valais (depuis 1865). Visite avec dégustation des bières locales.', 46.23, 7.36, 90, 2, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Amis'], true, false, 'https://www.valaisanne.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Brasserie Valaisanne' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Brasserie Valaisanne' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Caveau de Salquenen', 'Salquenen', 'gastronomy', 'Plus de 60 vignerons de Salgesch présentent leurs vins. Idéal pour découvrir le Pinot Noir.', 46.3083, 7.5667, 120, 2, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis'], true, false, 'https://www.salgesch.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Caveau de Salquenen' AND location_name = 'Salquenen') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Caveau de Salquenen' AND location_name = 'Salquenen');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Restaurant Ogo Sion', 'Sion', 'gastronomy', 'Restaurant tendance, cuisine fusion locale. Brunch dominical réputé.', 46.23, 7.36, 120, 3, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Amis','Famille'], true, false, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Restaurant Ogo Sion' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Restaurant Ogo Sion' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Verbier 4 Vallées', 'Verbier', 'sport', '412 km de pistes, 92 remontées. Plus grand domaine de Suisse romande, cadre Mont-Blanc.', 46.0961, 7.2286, 480, 5, ARRAY['Parking','Reservation necessaire'], ARRAY['Hiver'], ARRAY['Famille','Amis','Couple'], false, true, 'https://www.verbier.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[12,1,2,3,4]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Verbier 4 Vallées' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Verbier 4 Vallées' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Crans-Montana', 'Crans-Montana', 'sport', '140 km de pistes ensoleillées, vue 360° sur les Alpes. Domaine de prestige.', 46.3117, 7.4853, 480, 5, ARRAY['Parking'], ARRAY['Hiver'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.crans-montana.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[12,1,2,3,4]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Crans-Montana' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Crans-Montana' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Zermatt-Cervinia', 'Zermatt', 'sport', '360 km de pistes Suisse + Italie. Glacier ouvert à l''année. Vue Cervin partout.', 46.0207, 7.7491, 480, 5, ARRAY['Parking'], ARRAY['Été','Hiver','Automne'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.zermatt.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Zermatt-Cervinia' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Zermatt-Cervinia' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Saas-Fee', 'Saas-Fee', 'sport', '150 km de pistes au pied du Dom. Glacier accessible été comme hiver. Village sans voiture.', 46.1086, 7.9272, 480, 5, ARRAY['Parking'], ARRAY['Été','Hiver','Automne'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.saas-fee.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Saas-Fee' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Saas-Fee' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Champéry Portes du Soleil', 'Champéry', 'sport', 'Domaine franco-suisse de 600 km de pistes. 12 stations reliées, ambiance internationale.', 46.175, 6.8722, 480, 5, ARRAY['Parking'], ARRAY['Hiver'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.portesdusoleil.com', NULL, 'loc_lower', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[12,1,2,3,4]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Champéry Portes du Soleil' AND location_name = 'Champéry') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Champéry Portes du Soleil' AND location_name = 'Champéry');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Ski Anzère', 'Anzère', 'sport', '60 km de pistes, station familiale, vue impressionnante sur la vallée du Rhône.', 46.2842, 7.4108, 480, 4, ARRAY['Parking'], ARRAY['Hiver'], ARRAY['Famille'], false, true, 'https://www.anzere.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[12,1,2,3,4]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Ski Anzère' AND location_name = 'Anzère') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Ski Anzère' AND location_name = 'Anzère');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'VTT Verbier Bikepark', 'Verbier', 'sport', 'Plus grand bike park de Suisse romande. Pistes pour tous niveaux, remontées vélos.', 46.0961, 7.2286, 360, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Solo','Amis'], false, true, 'https://www.verbier.ch/ete/bikepark', NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'VTT Verbier Bikepark' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'VTT Verbier Bikepark' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Sierre-Zinal Trail', 'Sierre', 'sport', 'Course mythique de trail running (31 km, 2200m D+). Pour participer ou regarder en août.', 46.2925, 7.5356, 480, 1, ARRAY['Reservation necessaire'], ARRAY['Été'], ARRAY['Solo','Amis'], false, true, 'https://www.sierre-zinal.com', NULL, 'loc_central', 'Août 2026', 'August 2026', '2026-08-08'::date, '2026-08-09'::date, 'one_off', NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Sierre-Zinal Trail' AND location_name = 'Sierre') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Sierre-Zinal Trail' AND location_name = 'Sierre');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Téléphérique du Petit Cervin', 'Zermatt', 'sport', 'Plus haut téléphérique d''Europe (3883m). Glacier paradise, ski d''été possible.', 45.9389, 7.7178, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Été','Hiver','Automne'], ARRAY['Couple','Amis','Famille'], false, true, 'https://www.matterhornparadise.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Téléphérique du Petit Cervin' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Téléphérique du Petit Cervin' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cabane des Becs de Bosson', 'Arolla', 'sport', 'Randonnée alpine d''une journée vers la cabane (2785m). Refuge avec vue, repas chauds.', 46.025, 7.4889, 360, 3, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Solo','Amis'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cabane des Becs de Bosson' AND location_name = 'Arolla') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cabane des Becs de Bosson' AND location_name = 'Arolla');
