INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Gornergrat Bahn', 'Zermatt', 'nature', 'Train à crémaillère vers 3089m face au Cervin. Plus haut chemin de fer à ciel ouvert d''Europe.', 45.9839, 7.7956, 240, 5, ARRAY['Parking','Reservation necessaire'], ARRAY['Été','Automne','Hiver'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.gornergrat.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Gornergrat Bahn' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Gornergrat Bahn' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Glacier d''Aletsch', 'Bettmeralp', 'nature', 'Plus grand glacier des Alpes (23 km). Sites UNESCO, accès en téléphérique.', 46.4361, 8.0386, 360, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Couple','Amis','Famille'], false, true, 'https://www.aletscharena.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Glacier d''Aletsch' AND location_name = 'Bettmeralp') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Glacier d''Aletsch' AND location_name = 'Bettmeralp');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Lac d''Émosson', 'Finhaut', 'nature', 'Barrage et lac de montagne à 1930m. Empreintes de dinosaures, train du Mont-Blanc.', 46.0731, 6.9242, 360, 3, ARRAY['Parking','Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Famille','Couple','Amis'], false, true, 'https://www.verticalp-emosson.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Lac d''Émosson' AND location_name = 'Finhaut') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Lac d''Émosson' AND location_name = 'Finhaut');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Pyramides d''Euseigne', 'Euseigne', 'nature', 'Formations rocheuses uniques en Europe : colonnes de moraine coiffées de blocs rocheux.', 46.17, 7.435, 60, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], false, true, 'https://www.evolene-region.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Pyramides d''Euseigne' AND location_name = 'Euseigne') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Pyramides d''Euseigne' AND location_name = 'Euseigne');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bisse de Clavau', 'Sion', 'nature', 'Le plus accessible des bisses, le long des vignes. Vue sur Sion et la vallée du Rhône.', 46.2208, 7.3889, 180, 1, ARRAY[]::text[], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], false, true, 'https://www.siontourisme.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bisse de Clavau' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bisse de Clavau' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Lac Bleu d''Arolla', 'Arolla', 'nature', 'Petit lac de montagne à 2090m. Couleur turquoise saisissante. Accès randonnée 1h.', 46.0322, 7.485, 240, 1, ARRAY[]::text[], ARRAY['Été','Automne'], ARRAY['Couple','Solo','Amis'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Lac Bleu d''Arolla' AND location_name = 'Arolla') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Lac Bleu d''Arolla' AND location_name = 'Arolla');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Mont Fort', 'Verbier', 'nature', 'Sommet à 3328m accessible en téléphérique. Vue 360° sur 4000m suisses, italiens et français.', 46.0833, 7.3056, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Été','Hiver'], ARRAY['Couple','Amis'], false, true, 'https://www.verbier4vallees.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Mont Fort' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Mont Fort' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Cabane des Vignettes', 'Arolla', 'nature', 'Refuge alpin à 3160m, base pour la haute route Chamonix-Zermatt. Panorama exceptionnel.', 45.9889, 7.45, 480, 3, ARRAY['Reservation necessaire'], ARRAY['Été'], ARRAY['Solo','Amis','Couple'], false, true, 'https://www.cabanedesvignettes.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Cabane des Vignettes' AND location_name = 'Arolla') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Cabane des Vignettes' AND location_name = 'Arolla');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Lac de Tseuzier', 'Anzère', 'nature', 'Lac de barrage à 1777m, sentier autour. Vue Bernoises et Valaisannes.', 46.3506, 7.4111, 180, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Lac de Tseuzier' AND location_name = 'Anzère') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Lac de Tseuzier' AND location_name = 'Anzère');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Gorges du Trient', 'Vernayaz', 'nature', 'Sentier suspendu dans une gorge profonde de 100m, sur 750m. Cascade impressionnante.', 46.1311, 7.0497, 90, 2, ARRAY['Parking','Horaires restreints'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], false, true, 'https://www.gorgesdutrient.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Gorges du Trient' AND location_name = 'Vernayaz') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Gorges du Trient' AND location_name = 'Vernayaz');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Lac de Salanfe', 'Mex', 'nature', 'Lac alpin à 1925m entouré de sommets. Randonnée 4h depuis Van d''En Haut.', 46.1639, 7.0306, 360, 1, ARRAY[]::text[], ARRAY['Été','Automne'], ARRAY['Solo','Amis','Couple'], false, true, NULL, NULL, 'loc_lower', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Lac de Salanfe' AND location_name = 'Mex') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Lac de Salanfe' AND location_name = 'Mex');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Pic Chaussy', 'Les Mosses', 'nature', 'Sommet de 2351m accessible en 4h depuis Lausenen. Vue Diablerets + Cervin.', 46.3792, 7.1417, 360, 1, ARRAY[]::text[], ARRAY['Été','Automne'], ARRAY['Solo','Amis','Couple'], false, true, NULL, NULL, 'loc_lower', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Pic Chaussy' AND location_name = 'Les Mosses') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Pic Chaussy' AND location_name = 'Les Mosses');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Dent du Midi', 'Champéry', 'nature', 'Massif emblématique des 7 sommets. Tour de la Dent du Midi : 4 jours de rando inoubliable.', 46.1644, 6.9233, 480, 2, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Solo','Amis'], false, true, 'https://www.champery.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Dent du Midi' AND location_name = 'Champéry') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Dent du Midi' AND location_name = 'Champéry');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Champ de tulipes Saxon', 'Saxon', 'nature', 'Champs de tulipes spectaculaires en avril-mai. Photos garanties, gratuit.', 46.15, 7.175, 60, 1, ARRAY['Parking'], ARRAY['Printemps'], ARRAY['Famille','Couple','Solo'], false, true, NULL, NULL, 'loc_central', 'Avril-mai', 'April-May', NULL, NULL, 'seasonal', ARRAY[4,5]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Champ de tulipes Saxon' AND location_name = 'Saxon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Champ de tulipes Saxon' AND location_name = 'Saxon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Lac de Montorge', 'Sion', 'nature', 'Petit lac à proximité de Sion, sentier didactique nature, observation oiseaux.', 46.2417, 7.3406, 90, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo','Couple'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Lac de Montorge' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Lac de Montorge' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bisse du Ro', 'Crans-Montana', 'nature', 'Bisse spectaculaire creusé dans la falaise. Vues vertigineuses, pas pour le vertige.', 46.3083, 7.4889, 180, 1, ARRAY[]::text[], ARRAY['Printemps','Été','Automne'], ARRAY['Solo','Amis','Couple'], false, true, 'https://www.crans-montana.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bisse du Ro' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bisse du Ro' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Riffelsee', 'Zermatt', 'nature', 'Petit lac à 2757m offrant un reflet parfait du Cervin. Spot photo iconique de Suisse.', 45.9892, 7.7642, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Été','Automne'], ARRAY['Couple','Solo','Amis'], false, true, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Riffelsee' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Riffelsee' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Marais des Iles Sion', 'Sion', 'nature', 'Réserve naturelle aux portes de Sion. Sentiers, oiseaux migrateurs, étangs.', 46.2278, 7.3556, 90, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Marais des Iles Sion' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Marais des Iles Sion' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Château de Valère', 'Sion', 'culture', 'Forteresse médiévale et basilique avec le plus ancien orgue jouable du monde (1430).', 46.23, 7.3636, 120, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Famille','Solo'], true, true, 'https://www.musees-valais.ch/musee-d-histoire', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Château de Valère' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Château de Valère' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Château de Tourbillon', 'Sion', 'culture', 'Ruines d''un château épiscopal du XIIIe siècle, vue 360° sur la vallée du Rhône.', 46.2347, 7.3614, 90, 1, ARRAY[]::text[], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Couple','Solo'], false, true, 'https://www.siontourisme.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Château de Tourbillon' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Château de Tourbillon' AND location_name = 'Sion');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Abbaye de Saint-Maurice', 'Saint-Maurice', 'culture', 'Plus ancien monastère d''Europe occidentale (515). Trésor avec joaillerie millénaire.', 46.2189, 7.0064, 120, 2, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne'], ARRAY['Couple','Famille','Solo'], true, false, 'https://www.abbaye-stmaurice.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Abbaye de Saint-Maurice' AND location_name = 'Saint-Maurice') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Abbaye de Saint-Maurice' AND location_name = 'Saint-Maurice');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée et Chiens du Saint-Bernard', 'Martigny', 'culture', 'Histoire des chiens du col, chenil avec vrais saint-bernards à voir et caresser.', 46.1011, 7.075, 120, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille'], true, false, 'https://www.museesaintbernard.ch', NULL, 'loc_lower', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée et Chiens du Saint-Bernard' AND location_name = 'Martigny') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée et Chiens du Saint-Bernard' AND location_name = 'Martigny');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée du Lötschental', 'Kippel', 'culture', 'Musée régional des traditions du Lötschental : masques, costumes, art populaire.', 46.4133, 7.7867, 90, 2, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple','Solo'], true, false, 'https://www.loetschentalermuseum.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée du Lötschental' AND location_name = 'Kippel') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée du Lötschental' AND location_name = 'Kippel');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée des bisses', 'Botyre', 'culture', 'Musée consacré aux bisses du Valais. Maquettes, vidéos, sentier didactique.', 46.2433, 7.4444, 90, 2, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo'], true, false, 'https://www.musee-des-bisses.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée des bisses' AND location_name = 'Botyre') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée des bisses' AND location_name = 'Botyre');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Musée d''art du Valais', 'Sion', 'culture', 'Collections d''art du XVIIe siècle à nos jours. Expositions temporaires de qualité.', 46.2306, 7.3603, 90, 2, ARRAY[]::text[], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Solo','Couple'], true, false, 'https://www.musees-valais.ch/musee-d-art', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Musée d''art du Valais' AND location_name = 'Sion') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Musée d''art du Valais' AND location_name = 'Sion');
