INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Therme 51° Loèche-les-Bains', 'Loèche-les-Bains', 'relax', 'Centre thermal 5*, eau sulfureuse a 51°C. Bassins panoramiques, hammam alpin, soins exclusifs.', 46.385, 7.6311, 240, 5, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.51grad.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Therme 51° Loèche-les-Bains' AND location_name = 'Loèche-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Therme 51° Loèche-les-Bains' AND location_name = 'Loèche-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Bains de Saillon', 'Saillon', 'relax', 'Centre thermal moderne en plaine du Rhone. 4 bassins, sauna, hammam, fitness. Eau a 33°C.', 46.175, 7.1833, 240, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Famille','Couple'], true, true, 'https://www.bainsdesaillon.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Bains de Saillon' AND location_name = 'Saillon') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Bains de Saillon' AND location_name = 'Saillon');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Walliser Alpentherme Leukerbad', 'Loèche-les-Bains', 'relax', 'Centre thermal du Lindner Hotel. Bassins interieur/exterieur, sauna nordique, hammam romain, vue Alpes.', 46.3856, 7.6306, 240, 4, ARRAY['Parking','Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, true, 'https://www.alpentherme.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Walliser Alpentherme Leukerbad' AND location_name = 'Loèche-les-Bains') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Walliser Alpentherme Leukerbad' AND location_name = 'Loèche-les-Bains');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa W Verbier', 'Verbier', 'relax', 'Spa AWAY du W Hotel Verbier 5*. Piscine inox, hammam, sauna, soins design, vue Combin.', 46.0961, 7.2286, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.marriott.com/wver', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa W Verbier' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa W Verbier' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Chalet d''Adrien', 'Verbier', 'relax', 'Spa du Chalet d''Adrien (Relais & Châteaux). Piscine intérieure, soins exclusifs, ambiance alpine de luxe.', 46.0961, 7.2286, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.chalet-adrien.com', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Chalet d''Adrien' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Chalet d''Adrien' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Cordée des Alpes', 'Verbier', 'relax', 'Spa 5* de l''hotel La Cordée des Alpes. Piscine couverte, sauna, hammam, soins haut de gamme.', 46.0961, 7.2286, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.hotelcordee.com', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Cordée des Alpes' AND location_name = 'Verbier') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Cordée des Alpes' AND location_name = 'Verbier');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Hôtel Nendaz 4 Vallées Spa', 'Nendaz', 'relax', 'Spa 4* du Hôtel Nendaz 4 Vallées. Piscine, sauna, hammam, soins, vue station 4 Vallées.', 46.1839, 7.3092, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.hotelnendaz4vallees.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Hôtel Nendaz 4 Vallées Spa' AND location_name = 'Nendaz') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Hôtel Nendaz 4 Vallées Spa' AND location_name = 'Nendaz');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Backstage Hotel Zermatt', 'Zermatt', 'relax', 'Spa boutique de l''hotel Backstage (du chef Heinz Julen). Piscine, sauna, soins, design avant-gardiste.', 46.0207, 7.7491, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.backstagehotel.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Backstage Hotel Zermatt' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Backstage Hotel Zermatt' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Cervo Mountain Resort', 'Zermatt', 'relax', 'Spa du Cervo Resort 5*. Piscines panoramiques, hammam, sauna face au Cervin, soins valaisans.', 46.0207, 7.7491, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.cervo.swiss', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Cervo Mountain Resort' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Cervo Mountain Resort' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Schweizerhof Zermatt', 'Zermatt', 'relax', 'Spa 5* du Grand Hotel Schweizerhof. Piscine indoor, sauna, hammam, soins, vue Cervin.', 46.0207, 7.7491, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.grandhotelzermatterhof.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Schweizerhof Zermatt' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Schweizerhof Zermatt' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Mirabeau Zermatt', 'Zermatt', 'relax', 'Spa de l''hotel Mirabeau 4*. Piscine, sauna, hammam, soins, ambiance familiale alpine.', 46.0207, 7.7491, 150, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.hotel-mirabeau.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Mirabeau Zermatt' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Mirabeau Zermatt' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Park Hotel Beau-Site Zermatt', 'Zermatt', 'relax', 'Spa 5* du Park Hotel Beau-Site. Piscine, sauna finlandais, hammam, soins, vue Cervin depuis le toit.', 46.0207, 7.7491, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.parkhotel-beausite.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Park Hotel Beau-Site Zermatt' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Park Hotel Beau-Site Zermatt' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa La Couronne Zermatt', 'Zermatt', 'relax', 'Spa de l''hotel La Couronne 4*. Piscine, sauna, hammam, soins, ambiance traditionnelle.', 46.0207, 7.7491, 120, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.hotelcouronne.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa La Couronne Zermatt' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa La Couronne Zermatt' AND location_name = 'Zermatt');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Hôtel Bella Tola Spa', 'Saint-Luc', 'relax', 'Spa du Bella Tola 4*+ (Swiss Historic Hotel). Piscine couverte, sauna, hammam, ambiance Belle Epoque.', 46.2178, 7.6122, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.bellatola.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Hôtel Bella Tola Spa' AND location_name = 'Saint-Luc') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Hôtel Bella Tola Spa' AND location_name = 'Saint-Luc');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Mountain Lodge Saas-Fee', 'Saas-Fee', 'relax', 'Spa 4*+ du Mountain Lodge. Piscine intérieure, sauna, hammam, soins, ambiance chalet contemporain.', 46.1086, 7.9272, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Mountain Lodge Saas-Fee' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Mountain Lodge Saas-Fee' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Walliserhof Saas-Fee', 'Saas-Fee', 'relax', 'Spa du Walliserhof Grand Hotel 4*+. Piscine, sauna, hammam, soins, ambiance alpine traditionnelle.', 46.1086, 7.9272, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.walliserhof-saasfee.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Walliserhof Saas-Fee' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Walliserhof Saas-Fee' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Beau-Site Saas-Fee', 'Saas-Fee', 'relax', 'Spa de l''hotel Beau-Site 4*. Piscine panoramique sur les 4000m, sauna, hammam, soins.', 46.1086, 7.9272, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.beausite.ch', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Beau-Site Saas-Fee' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Beau-Site Saas-Fee' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa La Ferme Saas-Fee', 'Saas-Fee', 'relax', 'Spa boutique de la Ferme. Sauna, hammam, soins corps et visage, ambiance chalet de charme.', 46.1086, 7.9272, 120, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, NULL, NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa La Ferme Saas-Fee' AND location_name = 'Saas-Fee') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa La Ferme Saas-Fee' AND location_name = 'Saas-Fee');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa LeCrans Hotel', 'Crans-Montana', 'relax', 'Spa du LeCrans Hotel 5* (Relais & Châteaux). Piscine indoor, hammam, soins exclusifs, vue Alpes.', 46.3117, 7.4853, 240, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.lecrans.com', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa LeCrans Hotel' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa LeCrans Hotel' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Royal Hotel Crans', 'Crans-Montana', 'relax', 'Spa du Royal Hotel 5*. Piscine 25m, sauna, hammam, soins du visage et corps haut de gamme.', 46.3117, 7.4853, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.hotel-royal.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Royal Hotel Crans' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Royal Hotel Crans' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Faern Crans-Montana', 'Crans-Montana', 'relax', 'Spa du Faern Crans-Montana 4*+ (ex Mont-Blanc). Piscine, sauna, hammam, soins, terrasse vue Alpes.', 46.3117, 7.4853, 180, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, true, 'https://www.faern.com', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Faern Crans-Montana' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Faern Crans-Montana' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Pas de l''Ours', 'Crans-Montana', 'relax', 'Spa boutique du Pas de l''Ours 5*. Piscine, sauna, hammam, soins exclusifs, ambiance feutree.', 46.3117, 7.4853, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple'], true, false, 'https://www.pasdelours.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Pas de l''Ours' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Pas de l''Ours' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Spa Helvetia Intergolf', 'Crans-Montana', 'relax', 'Spa de l''hotel 4* Helvetia Intergolf. Piscine, sauna, hammam, soins, vue golf et Alpes.', 46.3117, 7.4853, 150, 4, ARRAY['Reservation necessaire'], ARRAY['Printemps','Été','Automne','Hiver'], ARRAY['Couple','Famille'], true, false, 'https://www.helvetia-intergolf.ch', NULL, 'loc_central', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Spa Helvetia Intergolf' AND location_name = 'Crans-Montana') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Spa Helvetia Intergolf' AND location_name = 'Crans-Montana');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Sentier des Bisses sereins', 'Anzère', 'relax', 'Parcours zen le long des bisses d''Anzere : eau qui coule, panoramas alpins, points meditation. Ideal forest bathing alpin.', 46.2842, 7.4108, 180, 1, ARRAY['Parking'], ARRAY['Printemps','Été','Automne'], ARRAY['Famille','Solo','Couple'], false, true, NULL, NULL, 'loc_central', NULL, NULL, NULL, NULL, 'seasonal', ARRAY[4,5,6,7,8,9,10]::int[], NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Sentier des Bisses sereins' AND location_name = 'Anzère') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Sentier des Bisses sereins' AND location_name = 'Anzère');

INSERT INTO activity_submissions (title, location_name, category, description, latitude, longitude, duration_minutes, price_level, features, seasons, social_tags, is_indoor, is_outdoor, activity_url, image_url, location_zone, date_label, date_label_en, date_start, date_end, recurrence_type, seasonal_months, weekly_days, status, submitted_by)
SELECT 'Sauna panoramique Riffelalp Resort', 'Zermatt', 'relax', 'Sauna et bains chauds extérieurs a 2''222m face au Cervin. Plus haut spa hotel d''Europe (Riffelalp Resort 5*).', 46.0064, 7.7611, 180, 5, ARRAY['Reservation necessaire'], ARRAY['Été','Automne','Hiver'], ARRAY['Couple'], true, true, 'https://www.riffelalp.com', NULL, 'loc_upper', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pending', NULL
WHERE NOT EXISTS (SELECT 1 FROM activity_submissions WHERE title = 'Sauna panoramique Riffelalp Resort' AND location_name = 'Zermatt') AND NOT EXISTS (SELECT 1 FROM activities WHERE title = 'Sauna panoramique Riffelalp Resort' AND location_name = 'Zermatt');
