-- Whateka - Seed 70 Valais activities (pending submissions)
-- Categories restricted to: nature, culture, gastronomy, sport, adventure, fun
-- image_url / activity_url left NULL, to be filled by batch-enrich-pending edge function.

INSERT INTO public.activity_submissions
  (status, archived, location_zone, submitted_by, title, location_name, description, category,
   latitude, longitude, duration_minutes, price_level, is_indoor, is_outdoor, features, seasons, social_tags)
VALUES
-- ===== SION / CENTRE =====
('pending', false, 'valais', 'seed-script', 'Cathédrale Notre-Dame de Sion', 'Sion', 'Cathédrale gothique au cœur de la vieille ville de Sion, joyau d''architecture religieuse valaisanne.', 'culture', 46.2336, 7.3596, 45, 0, true, false, ARRAY['photo','famille']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['culture','histoire']::text[]),
('pending', false, 'valais', 'seed-script', 'Château de Valère', 'Sion', 'Forteresse médiévale perchée sur sa colline, abritant l''un des plus anciens orgues jouables du monde et un musée d''histoire.', 'culture', 46.2331, 7.3633, 90, 1, true, true, ARRAY['photo','vue','famille']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['histoire','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Château de Tourbillon', 'Sion', 'Ruines romantiques perchées au sommet de la colline jumelle de Valère, vue à 360° sur la vallée du Rhône.', 'culture', 46.2363, 7.3618, 75, 0, false, true, ARRAY['photo','vue','marche']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['panorama','histoire']::text[]),
('pending', false, 'valais', 'seed-script', 'Musée d''art du Valais', 'Sion', 'Collection riche d''art valaisan et suisse du Moyen Âge à aujourd''hui, dans l''ancien château épiscopal.', 'culture', 46.2326, 7.3582, 90, 1, true, false, ARRAY['photo','calme']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['art','culture']::text[]),
('pending', false, 'valais', 'seed-script', 'Bisse de Clavau', 'Sion', 'Bisse historique le long des vignobles ensoleillés de Sion à Saint-Léonard, classé patrimoine UNESCO.', 'nature', 46.2300, 7.4000, 180, 0, false, true, ARRAY['marche','photo','vignes']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['randonnee','patrimoine']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac souterrain de Saint-Léonard', 'Saint-Léonard', 'Plus grand lac souterrain naturel d''Europe, visite en barque dans une grotte impressionnante.', 'fun', 46.2540, 7.4180, 60, 2, true, false, ARRAY['famille','photo','insolite']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['insolite','famille']::text[]),
('pending', false, 'valais', 'seed-script', 'Mont d''Orge', 'Sion', 'Petite colline avec étang et ruines de château, balade facile au-dessus de Sion avec vue sur les vignes.', 'nature', 46.2226, 7.3306, 90, 0, false, true, ARRAY['marche','famille','calme']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['nature','panorama']::text[]),

-- ===== SIERRE / VAL D'ANNIVIERS =====
('pending', false, 'valais', 'seed-script', 'Lac de Géronde', 'Sierre', 'Lac de baignade familial entouré de vignes et de collines, plage de sable et restaurants.', 'nature', 46.2860, 7.5390, 120, 0, false, true, ARRAY['baignade','famille','calme']::text[], ARRAY['ete']::text[], ARRAY['baignade','famille']::text[]),
('pending', false, 'valais', 'seed-script', 'Musée du Vin de Sierre', 'Sierre', 'Musée valaisan dédié à la vigne et au vin, parcours interactif sur la viticulture cantonale.', 'culture', 46.2917, 7.5358, 75, 1, true, false, ARRAY['degustation','culture']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['vin','culture']::text[]),
('pending', false, 'valais', 'seed-script', 'Sentier viticole Sierre-Salgesch', 'Sierre', 'Sentier didactique de 6 km à travers les vignobles entre Sierre et Salgesch, panneaux explicatifs et points de dégustation.', 'gastronomy', 46.3000, 7.5500, 150, 1, false, true, ARRAY['vignes','marche','degustation']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['vin','randonnee']::text[]),
('pending', false, 'valais', 'seed-script', 'Funiculaire SMC Sierre - Crans-Montana', 'Sierre', 'Funiculaire historique reliant Sierre à la station de Crans-Montana en 12 minutes, magnifiques vues sur la vallée.', 'fun', 46.3091, 7.4827, 30, 1, true, true, ARRAY['vue','famille']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['transport','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac de Moiry', 'Grimentz', 'Lac de barrage d''un bleu intense entouré de sommets, sentier autour du lac et glacier accessible en été.', 'nature', 46.1300, 7.5900, 180, 0, false, true, ARRAY['vue','marche','photo']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','montagne']::text[]),
('pending', false, 'valais', 'seed-script', 'Village de Grimentz', 'Grimentz', 'Un des plus beaux villages du Valais, ruelles fleuries de géraniums, raccards en bois noirci par le soleil.', 'culture', 46.1800, 7.5750, 90, 0, false, true, ARRAY['photo','village','famille']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['patrimoine','village']::text[]),
('pending', false, 'valais', 'seed-script', 'Téléphérique Sorebois', 'Zinal', 'Remontée mécanique offrant un panorama sur la Couronne Impériale (Cervin, Dent Blanche, Weisshorn).', 'sport', 46.1700, 7.5700, 120, 2, false, true, ARRAY['vue','randonnee','panorama']::text[], ARRAY['ete','automne','hiver']::text[], ARRAY['montagne','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Pinède de Finges', 'Sierre', 'Plus grande pinède d''Europe centrale, réserve naturelle entre Sierre et Loèche avec sentiers et étangs.', 'nature', 46.3000, 7.6100, 180, 0, false, true, ARRAY['marche','calme','famille']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['foret','randonnee']::text[]),

-- ===== CRANS-MONTANA / ANZÈRE =====
('pending', false, 'valais', 'seed-script', 'Bisse du Ro', 'Crans-Montana', 'Bisse vertigineux taillé dans la falaise, traverse les Gorges de la Tièche au-dessus de Crans-Montana.', 'adventure', 46.3100, 7.4700, 240, 0, false, true, ARRAY['marche','sensations','vue']::text[], ARRAY['ete','automne']::text[], ARRAY['randonnee','vertige']::text[]),
('pending', false, 'valais', 'seed-script', 'Glacier de la Plaine Morte', 'Crans-Montana', 'Plus grand glacier de plateau des Alpes, accessible via le téléphérique du Cry d''Er, paysage lunaire.', 'sport', 46.3853, 7.4944, 240, 3, false, true, ARRAY['vue','randonnee','panorama']::text[], ARRAY['ete','hiver']::text[], ARRAY['glacier','montagne']::text[]),
('pending', false, 'valais', 'seed-script', 'Aminona Tubing', 'Aminona', 'Piste de luge d''été sur bouée gonflable, descente ludique et rafraîchissante pour toute la famille.', 'fun', 46.3300, 7.5000, 60, 2, false, true, ARRAY['famille','sensations','fun']::text[], ARRAY['ete']::text[], ARRAY['famille','adrenaline']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac de Tseuzier', 'Ayent', 'Lac de barrage turquoise dans un cirque montagneux, sentier panoramique et excellent point de départ de randonnées.', 'nature', 46.3300, 7.4100, 180, 0, false, true, ARRAY['vue','marche','photo']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','montagne']::text[]),
('pending', false, 'valais', 'seed-script', 'Bisse du Torrent-Neuf de Savièse', 'Savièse', 'Bisse rénové serpentant à flanc de falaise avec passerelles spectaculaires, vue plongeante sur la vallée du Rhône.', 'adventure', 46.2700, 7.3300, 180, 0, false, true, ARRAY['marche','sensations','vue']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['randonnee','vertige']::text[]),
('pending', false, 'valais', 'seed-script', 'Pas de Maimbré', 'Anzère', 'Sommet accessible en télésiège depuis Anzère, panorama sur les Alpes valaisannes et bernoises.', 'sport', 46.3000, 7.3800, 150, 2, false, true, ARRAY['vue','randonnee','panorama']::text[], ARRAY['ete','automne','hiver']::text[], ARRAY['montagne','panorama']::text[]),

-- ===== VAL D'HÉRENS =====
('pending', false, 'valais', 'seed-script', 'Pyramides d''Euseigne', 'Hérémence', 'Formations rocheuses spectaculaires sculptées par l''érosion glaciaire, coiffées de chapeaux de pierre.', 'nature', 46.1500, 7.4200, 45, 0, false, true, ARRAY['photo','famille','curiosite']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['geologie','insolite']::text[]),
('pending', false, 'valais', 'seed-script', 'Barrage de la Grande Dixence', 'Hérémence', 'Plus haut barrage-poids du monde (285 m), visite guidée à l''intérieur et téléphérique jusqu''à la crête.', 'culture', 46.0810, 7.4040, 180, 2, true, true, ARRAY['vue','curiosite','famille']::text[], ARRAY['ete','automne']::text[], ARRAY['ingenierie','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac Bleu d''Arolla', 'Arolla', 'Petit lac d''un bleu intense au pied du glacier d''Arolla, accessible par une randonnée familiale depuis La Gouille.', 'nature', 46.0500, 7.4700, 150, 0, false, true, ARRAY['marche','photo','famille']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','montagne']::text[]),
('pending', false, 'valais', 'seed-script', 'Village d''Evolène', 'Evolène', 'Village authentique du Val d''Hérens, maisons en mélèze brun, costumes traditionnels encore portés.', 'culture', 46.1117, 7.4906, 90, 0, false, true, ARRAY['photo','village','calme']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['patrimoine','village']::text[]),
('pending', false, 'valais', 'seed-script', 'Glacier de Ferpècle', 'Evolène', 'Randonnée vers les glaciers de Ferpècle et du Mont Miné, paysage minéral et alpages.', 'sport', 46.0600, 7.5400, 300, 0, false, true, ARRAY['vue','randonnee','sensations']::text[], ARRAY['ete','automne']::text[], ARRAY['glacier','randonnee']::text[]),

-- ===== VERBIER / VAL DE BAGNES =====
('pending', false, 'valais', 'seed-script', 'Mont-Fort', 'Verbier', 'Sommet à 3330 m accessible en téléphérique, panorama sur le Cervin, le Mont-Blanc et la Dent Blanche.', 'sport', 46.0900, 7.2900, 240, 3, false, true, ARRAY['vue','panorama','sensations']::text[], ARRAY['ete','hiver']::text[], ARRAY['montagne','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Sentier des Chamois', 'Verbier', 'Randonnée d''altitude entre les Ruinettes et la Chaux, observation possible de chamois et bouquetins.', 'nature', 46.0961, 7.2289, 180, 1, false, true, ARRAY['marche','animaux','vue']::text[], ARRAY['ete','automne']::text[], ARRAY['faune','randonnee']::text[]),
('pending', false, 'valais', 'seed-script', 'Parapente à Verbier', 'Verbier', 'Vol biplace en parapente au-dessus de la vallée de Bagnes, décollage du Croix-de-Coeur ou des Ruinettes.', 'adventure', 46.0961, 7.2289, 60, 4, false, true, ARRAY['sensations','vue','adrenaline']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['adrenaline','vol']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac des Vaux', 'Verbier', 'Lac alpin entouré de sommets au-dessus de Verbier, accessible à pied ou en télésiège depuis Tortin.', 'nature', 46.1100, 7.2700, 120, 1, false, true, ARRAY['marche','photo','calme']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','montagne']::text[]),
('pending', false, 'valais', 'seed-script', 'Barrage de Mauvoisin', 'Val de Bagnes', 'Spectaculaire barrage-voûte de 250 m, route panoramique en cul-de-sac dans une vallée sauvage.', 'culture', 46.0000, 7.3700, 180, 0, false, true, ARRAY['vue','famille','curiosite']::text[], ARRAY['ete','automne']::text[], ARRAY['ingenierie','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Cabane du Mont-Fort', 'Verbier', 'Refuge alpin du CAS à 2457 m, étape mythique sur le tour des Combins, vue exceptionnelle.', 'sport', 46.0700, 7.3000, 360, 1, true, true, ARRAY['randonnee','panorama','sensations']::text[], ARRAY['ete','automne']::text[], ARRAY['randonnee','refuge']::text[]),
('pending', false, 'valais', 'seed-script', 'VTT à Verbier Bikepark', 'Verbier', 'L''un des bikeparks les plus réputés de Suisse, dizaines de pistes pour tous niveaux entre 800 et 2500 m.', 'sport', 46.0961, 7.2289, 240, 3, false, true, ARRAY['sensations','adrenaline','sport']::text[], ARRAY['ete','automne']::text[], ARRAY['vtt','adrenaline']::text[]),

-- ===== MARTIGNY / VAL FERRET / ENTREMONT =====
('pending', false, 'valais', 'seed-script', 'Fondation Pierre Gianadda', 'Martigny', 'Centre culturel renommé : expositions d''art (Picasso, Monet...), musée gallo-romain et automobile, parc de sculptures.', 'culture', 46.1003, 7.0728, 150, 2, true, true, ARRAY['art','famille','culture']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['art','musee']::text[]),
('pending', false, 'valais', 'seed-script', 'Amphithéâtre romain de Martigny', 'Martigny', 'Vestiges d''un amphithéâtre romain du Ier siècle, scène de combats de reines (vaches d''Hérens).', 'culture', 46.1010, 7.0735, 30, 0, false, true, ARRAY['photo','famille','histoire']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['histoire','culture']::text[]),
('pending', false, 'valais', 'seed-script', 'Château de la Bâtiaz', 'Martigny', 'Forteresse médiévale dominant Martigny, accessible à pied par un sentier, salle d''armes et taverne.', 'culture', 46.1019, 7.0664, 90, 1, true, true, ARRAY['vue','famille','histoire']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['chateau','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Gorges du Durnand', 'Bovernier', 'Vertigineuses gorges aménagées de passerelles, parcours suspendu au-dessus du torrent, fraîcheur garantie.', 'nature', 46.0833, 7.1500, 90, 1, false, true, ARRAY['sensations','famille','photo']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['gorges','sensations']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac de Champex', 'Champex-Lac', 'Lac de montagne pittoresque entouré de chalets et de mélèzes, baignade et barques en été.', 'nature', 46.0294, 7.1158, 120, 0, false, true, ARRAY['baignade','calme','famille']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','calme']::text[]),
('pending', false, 'valais', 'seed-script', 'Jardin Alpin Flore-Alpe', 'Champex-Lac', 'Jardin botanique de montagne avec plus de 4000 espèces alpines, étangs et rocailles à 1500 m d''altitude.', 'nature', 46.0291, 7.1153, 90, 1, false, true, ARRAY['photo','calme','famille']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['botanique','nature']::text[]),
('pending', false, 'valais', 'seed-script', 'Val Ferret suisse', 'Orsières', 'Vallée alpine sauvage au pied du massif du Mont-Blanc, randonnées vers la Fouly et le glacier de Saleina.', 'sport', 46.0300, 7.1200, 300, 0, false, true, ARRAY['marche','panorama','calme']::text[], ARRAY['ete','automne']::text[], ARRAY['randonnee','montagne']::text[]),
('pending', false, 'valais', 'seed-script', 'Barrage et Lac d''Emosson', 'Finhaut', 'Lac de barrage d''altitude avec vue sur le massif du Mont-Blanc, fameux pour ses traces de dinosaures.', 'nature', 46.0683, 6.9347, 240, 2, false, true, ARRAY['vue','marche','famille']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'VerticAlp Emosson', 'Le Châtelard', 'Funiculaire le plus pentu du monde + petit train panoramique + funiculaire pour atteindre le barrage d''Emosson.', 'fun', 46.0570, 6.9670, 240, 3, true, true, ARRAY['sensations','famille','vue']::text[], ARRAY['ete','automne']::text[], ARRAY['famille','transport']::text[]),
('pending', false, 'valais', 'seed-script', 'Cascade de Pissevache', 'Vernayaz', 'Chute d''eau de 114 m visible depuis la route, particulièrement spectaculaire à la fonte des neiges.', 'nature', 46.1437, 7.0428, 30, 0, false, true, ARRAY['photo','famille','calme']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['cascade','nature']::text[]),
('pending', false, 'valais', 'seed-script', 'Gorges du Trient', 'Vernayaz', 'Gorges étroites et profondes aménagées d''une passerelle suspendue, eau d''un vert émeraude.', 'nature', 46.1370, 7.0290, 60, 1, false, true, ARRAY['sensations','photo','famille']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['gorges','nature']::text[]),

-- ===== ST-MAURICE / CHABLAIS =====
('pending', false, 'valais', 'seed-script', 'Abbaye de Saint-Maurice', 'Saint-Maurice', 'Abbaye fondée au 6e siècle, l''une des plus anciennes d''Occident, trésor exceptionnel d''orfèvrerie sacrée.', 'culture', 46.2200, 7.0040, 90, 1, true, true, ARRAY['histoire','calme','culture']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['religieux','histoire']::text[]),
('pending', false, 'valais', 'seed-script', 'Grotte aux Fées', 'Saint-Maurice', 'Grotte naturelle aménagée avec lac souterrain et cascade, sentier balisé et magnifique panorama à l''entrée.', 'fun', 46.2200, 7.0000, 75, 1, true, true, ARRAY['famille','insolite','photo']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['grotte','famille']::text[]),
('pending', false, 'valais', 'seed-script', 'Château de Saint-Maurice', 'Saint-Maurice', 'Château historique sur le défilé entre Vaud et Valais, musée militaire et expositions temporaires.', 'culture', 46.2189, 7.0033, 75, 1, true, false, ARRAY['histoire','famille','culture']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['chateau','musee']::text[]),
('pending', false, 'valais', 'seed-script', 'Labyrinthe Aventure Evionnaz', 'Evionnaz', 'Plus grand labyrinthe végétal permanent du monde, parcours d''aventure, animations et restaurant.', 'fun', 46.1850, 7.0260, 180, 2, false, true, ARRAY['famille','fun','aventure']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['famille','jeu']::text[]),
('pending', false, 'valais', 'seed-script', 'Bains de Saillon', 'Saillon', 'Centre thermal en plein cœur du Valais, bassins extérieurs et intérieurs, source à 28°C.', 'fun', 46.1820, 7.1820, 180, 3, true, true, ARRAY['detente','famille','bien-etre']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['bien-etre','famille']::text[]),
('pending', false, 'valais', 'seed-script', 'Bourg médiéval de Saillon', 'Saillon', 'Un des plus beaux bourgs médiévaux de Suisse, tour Bayart, remparts et sentier des vignes Farinet.', 'culture', 46.1773, 7.1825, 90, 0, false, true, ARRAY['photo','village','famille']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['patrimoine','village']::text[]),
('pending', false, 'valais', 'seed-script', 'Aquaparc du Bouveret', 'Le Bouveret', 'Plus grand parc aquatique de Suisse romande, toboggans, rivières et lagons tropicaux.', 'fun', 46.3850, 6.8550, 240, 3, true, true, ARRAY['famille','fun','sensations']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['famille','jeu']::text[]),
('pending', false, 'valais', 'seed-script', 'Swiss Vapeur Parc', 'Le Bouveret', 'Parc de mini-trains à vapeur dans un décor miniature des sites suisses, plaisir garanti pour les enfants.', 'fun', 46.3856, 6.8597, 150, 2, false, true, ARRAY['famille','fun','photo']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['famille','transport']::text[]),
('pending', false, 'valais', 'seed-script', 'Vouvry - Tanay', 'Vouvry', 'Lac de Tanay, l''un des plus beaux lacs de montagne de Suisse, atteint par une randonnée familiale.', 'nature', 46.3450, 6.8350, 240, 0, false, true, ARRAY['marche','photo','calme']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','randonnee']::text[]),

-- ===== CHAMPÉRY / VAL D'ILLIEZ =====
('pending', false, 'valais', 'seed-script', 'Téléphérique des Crosets - Champéry', 'Champéry', 'Accès aux Portes du Soleil, immense domaine de randonnée et VTT au cœur des Dents du Midi.', 'sport', 46.1761, 6.8633, 180, 3, false, true, ARRAY['vue','randonnee','vtt']::text[], ARRAY['ete','automne','hiver']::text[], ARRAY['montagne','randonnee']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac Vert de Morgins', 'Morgins', 'Petit lac émeraude au cœur d''une réserve naturelle, accessible par une balade familiale.', 'nature', 46.2400, 6.8650, 90, 0, false, true, ARRAY['marche','famille','calme']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['lac','nature']::text[]),

-- ===== LEUKERBAD / GEMMI =====
('pending', false, 'valais', 'seed-script', 'Bains de Leukerbad', 'Loèche-les-Bains', 'Plus grande station thermale alpine d''Europe, bassins chauds dans un cirque montagneux impressionnant.', 'fun', 46.3781, 7.6300, 180, 3, true, true, ARRAY['detente','famille','bien-etre']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['bien-etre','thermes']::text[]),
('pending', false, 'valais', 'seed-script', 'Gemmipass', 'Loèche-les-Bains', 'Col historique entre Valais et Berne accessible en téléphérique, panorama spectaculaire sur les Alpes valaisannes.', 'sport', 46.4067, 7.6128, 180, 3, false, true, ARRAY['vue','randonnee','panorama']::text[], ARRAY['ete','automne']::text[], ARRAY['montagne','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Daubensee', 'Loèche-les-Bains', 'Lac alpin au pied du Gemmipass, accessible à pied après le téléphérique, randonnée plate et famille.', 'nature', 46.4050, 7.6280, 120, 1, false, true, ARRAY['marche','calme','famille']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','altitude']::text[]),

-- ===== BRIGUE / HAUT-VALAIS / ALETSCH =====
('pending', false, 'valais', 'seed-script', 'Château Stockalper', 'Brigue', 'Plus grand palais privé du baroque suisse, ancienne résidence du marchand Kaspar Jodok von Stockalper.', 'culture', 46.3170, 7.9870, 90, 1, true, true, ARRAY['histoire','famille','culture']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['chateau','histoire']::text[]),
('pending', false, 'valais', 'seed-script', 'World Nature Forum', 'Naters', 'Centre d''interprétation interactif sur le patrimoine mondial UNESCO Jungfrau-Aletsch.', 'culture', 46.3260, 7.9870, 90, 2, true, false, ARRAY['famille','nature','culture']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['nature','musee']::text[]),
('pending', false, 'valais', 'seed-script', 'Aletsch Arena - Bettmeralp', 'Bettmeralp', 'Vue exceptionnelle sur le plus grand glacier des Alpes depuis le balcon de la Bettmeralp.', 'nature', 46.4060, 8.0410, 180, 2, false, true, ARRAY['vue','famille','randonnee']::text[], ARRAY['ete','automne','hiver']::text[], ARRAY['glacier','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Eggishorn', 'Fiesch', 'Sommet à 2926 m accessible en téléphérique, vue plongeante sur le glacier d''Aletsch, sentier crête.', 'sport', 46.4360, 8.0930, 180, 3, false, true, ARRAY['vue','randonnee','panorama']::text[], ARRAY['ete','automne']::text[], ARRAY['glacier','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Riederalp et Forêt d''Aletsch', 'Riederalp', 'Village sans voiture sur le balcon d''Aletsch, randonnées dans la forêt protégée d''arolles centenaires.', 'nature', 46.3960, 8.0290, 240, 2, false, true, ARRAY['marche','calme','famille']::text[], ARRAY['ete','automne','hiver']::text[], ARRAY['foret','glacier']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac de Märjelen', 'Fiescheralp', 'Lac glaciaire au pied du Grand Glacier d''Aletsch, randonnée d''altitude spectaculaire.', 'sport', 46.4360, 8.0700, 240, 1, false, true, ARRAY['vue','randonnee','photo']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','glacier']::text[]),
('pending', false, 'valais', 'seed-script', 'Bains de Brigerbad', 'Brigerbad', 'Plus grand parc thermal de plein air de Suisse, sources chaudes naturelles et toboggans.', 'fun', 46.3000, 7.9700, 180, 2, true, true, ARRAY['detente','famille','bien-etre']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['thermes','famille']::text[]),

-- ===== LÖTSCHENTAL =====
('pending', false, 'valais', 'seed-script', 'Lötschental - Fafleralp', 'Blatten', 'Vallée préservée et authentique, randonnées vers le glacier du Langgletscher dans un décor alpin pur.', 'nature', 46.4300, 7.7800, 300, 1, false, true, ARRAY['marche','calme','panorama']::text[], ARRAY['ete','automne']::text[], ARRAY['vallee','randonnee']::text[]),
('pending', false, 'valais', 'seed-script', 'Belalp', 'Blatten bei Naters', 'Plateau d''altitude avec vue plongeante sur le glacier d''Aletsch, départ de la fameuse passerelle suspendue.', 'sport', 46.3960, 8.0050, 180, 2, false, true, ARRAY['vue','randonnee','sensations']::text[], ARRAY['ete','automne']::text[], ARRAY['glacier','panorama']::text[]),

-- ===== ZERMATT =====
('pending', false, 'valais', 'seed-script', 'Gornergrat', 'Zermatt', 'Train à crémaillère mythique jusqu''à 3089 m, panorama à 360° sur 29 sommets de plus de 4000 m.', 'sport', 45.9836, 7.7867, 240, 4, true, true, ARRAY['vue','panorama','famille']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['montagne','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Riffelsee', 'Zermatt', 'Petit lac d''altitude célèbre pour son reflet parfait du Cervin, accessible depuis Rotenboden.', 'nature', 45.9869, 7.7547, 90, 2, false, true, ARRAY['photo','calme','marche']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Matterhorn Glacier Paradise', 'Zermatt', 'Plus haut téléphérique d''Europe (3883 m), grotte de glace, vue sur 38 glaciers et 14 pays.', 'sport', 45.9389, 7.7286, 240, 4, true, true, ARRAY['vue','panorama','sensations']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['glacier','altitude']::text[]),
('pending', false, 'valais', 'seed-script', 'Five Lakes Walk - Sunnegga', 'Zermatt', 'Randonnée familiale autour de 5 lacs alpins, dont le Stellisee qui reflète le Cervin.', 'nature', 46.0089, 7.7670, 240, 2, false, true, ARRAY['marche','photo','famille']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','randonnee']::text[]),
('pending', false, 'valais', 'seed-script', 'Matterhorn Museum Zermatlantis', 'Zermatt', 'Musée souterrain interactif sur l''histoire de Zermatt et la conquête du Cervin en 1865.', 'culture', 46.0202, 7.7491, 90, 2, true, false, ARRAY['histoire','famille','culture']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['musee','histoire']::text[]),
('pending', false, 'valais', 'seed-script', 'Gorner Gorge', 'Zermatt', 'Gorges étroites aux eaux turquoise creusées dans la roche serpentine, passerelles aménagées.', 'nature', 46.0150, 7.7470, 60, 1, false, true, ARRAY['photo','famille','sensations']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['gorges','nature']::text[]),

-- ===== SAAS-FEE =====
('pending', false, 'valais', 'seed-script', 'Mittelallalin - Saas-Fee', 'Saas-Fee', 'Plus haut métro souterrain du monde, restaurant tournant à 3500 m et grotte de glace au cœur du glacier.', 'sport', 46.0986, 7.9436, 240, 4, true, true, ARRAY['vue','sensations','famille']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['glacier','altitude']::text[]),
('pending', false, 'valais', 'seed-script', 'Hannigalp', 'Saas-Fee', 'Plateau d''altitude familial accessible en télésiège, parc de jeux et restaurants face aux 4000 m.', 'fun', 46.1120, 7.9280, 180, 2, false, true, ARRAY['famille','vue','fun']::text[], ARRAY['ete','automne','hiver']::text[], ARRAY['famille','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Lac de Mattmark', 'Saas-Almagell', 'Plus grand barrage en remblai d''Europe, sentier autour du lac, paysage alpin sauvage.', 'sport', 46.0494, 7.9614, 240, 0, false, true, ARRAY['marche','calme','vue']::text[], ARRAY['ete','automne']::text[], ARRAY['lac','randonnee']::text[]),
('pending', false, 'valais', 'seed-script', 'Felskinn - Saas-Fee', 'Saas-Fee', 'Première étape pour monter au Mittelallalin, vue spectaculaire sur le cirque glaciaire de Saas-Fee.', 'sport', 46.0944, 7.9300, 180, 3, false, true, ARRAY['vue','sensations','panorama']::text[], ARRAY['ete','automne','hiver']::text[], ARRAY['glacier','panorama']::text[]),

-- ===== GOMS / RHÔNE SUPÉRIEUR =====
('pending', false, 'valais', 'seed-script', 'Vallée de Conches (Goms) à vélo', 'Münster', 'Piste cyclable plate et bucolique le long du Rhône naissant, villages typiques en mélèze brun.', 'sport', 46.4940, 8.2680, 240, 0, false, true, ARRAY['velo','famille','calme']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['velo','vallee']::text[]),
('pending', false, 'valais', 'seed-script', 'Source du Rhône - Gletsch', 'Gletsch', 'Lieu de naissance du Rhône au pied du glacier, accessible par la route mythique de la Furka.', 'nature', 46.5680, 8.3700, 90, 0, false, true, ARRAY['photo','panorama','curiosite']::text[], ARRAY['ete','automne']::text[], ARRAY['glacier','curiosite']::text[]),
('pending', false, 'valais', 'seed-script', 'Glacier du Rhône - Grotte de glace', 'Oberwald', 'Tunnel de glace creusé chaque année dans le glacier du Rhône, accessible depuis le col de la Furka.', 'fun', 46.5750, 8.3850, 60, 2, false, true, ARRAY['curiosite','famille','photo']::text[], ARRAY['ete']::text[], ARRAY['glacier','insolite']::text[]),
('pending', false, 'valais', 'seed-script', 'Train Glacier Express (tronçon valaisan)', 'Brigue', 'Train panoramique entre Zermatt et St-Moritz, le tronçon Brigue-Disentis traverse les paysages les plus spectaculaires.', 'fun', 46.3170, 7.9870, 480, 4, true, false, ARRAY['vue','famille','panorama']::text[], ARRAY['printemps','ete','automne','hiver']::text[], ARRAY['transport','panorama']::text[]),

-- ===== VIGNOBLES & GASTRONOMIE =====
('pending', false, 'valais', 'seed-script', 'Vignoble en terrasses de Visperterminen', 'Visperterminen', 'L''un des vignobles les plus hauts d''Europe (1100 m), terrasses de Heida (Païen) et chemin viticole.', 'gastronomy', 46.2800, 7.8800, 180, 1, false, true, ARRAY['vignes','degustation','marche']::text[], ARRAY['ete','automne']::text[], ARRAY['vin','panorama']::text[]),
('pending', false, 'valais', 'seed-script', 'Chemin du Vignoble valaisan', 'Salgesch', 'Sentier balisé de 66 km à travers les vignes du Valais central, étapes dégustation et caves ouvertes.', 'gastronomy', 46.3120, 7.5680, 300, 1, false, true, ARRAY['vignes','marche','degustation']::text[], ARRAY['printemps','ete','automne']::text[], ARRAY['vin','randonnee']::text[]);
